### ISSUE TITLE
WindowPresenter variable #model should be renamed #presenter

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#10]
Don't forget the deprecation to not break current UIs

**Comment by estebanlm** [comment]
why it should be ?
it isn't a model of the presenter, regardless it is a presenter itself?

**Comment by jecisc** [comment]
Before it pointed to a *Model, now Model was renamed Presenter. 

It's to make the difference between the real model used by the GUI and the adaptor that is part of the GUI.
