### ISSUE TITLE
some demo are broken :(

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#1003]
SpDemoImagePresenter >> initializePresenters [
	image1 := self newImage.
	image2 := self newImage.

	image1 image: (self iconNamed: #pharo).
	image2 image: self currentWorld submorphs last form.
]

SpButtonPresenter >> addShortcutTipFor: aCharacter on: aString [
	
	^ aString withAccentuatedCharacter: aCharacter ]

**Comment by pavel-krivanek** [comment]
for the second case, the problem is in printing of shortcuts in `SpAbstractButtonPresenter>>#addShortcutTipFor:`, not in `withAccentuatedCharacter:`

**Comment by estebanlm** [comment]
everything seems to be working now (at least, I couldn't reproduce them)
