### ISSUE TITLE
Spec and newtool commitishes are outdated

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#1019]
```
loadIceberg
	...
	(Smalltalk classNamed: #IcePharoPlugin) 
		addPharoProjectToIceberg;
		addProjectNamed: 'pharo-spec2' commit: '15cacf316c2bf6e01eae348ac30523433476f1f8' baselines: #(BaselineOfSpec2);
		addProjectNamed: 'pharo-newtools' commit: '94785f82ef6288de4405b929d7b86faac582be5e' baselines: #(BaselineOfNewTools);
		addIcebergProjectToIceberg
```

**Comment by estebanlm** [comment]
Mmm... I´d like to find a better way to express this other than the commitish (maybe a tag?)... but I didn't find a good way when I first implemented this (and I think Martin didn't found it either)... any idea?

**Comment by estebanlm** [comment]
in anycase, I forgot to update them last merge... I will of course need to do it next one :)

**Comment by guillep** [comment]
I think the best is to have a branch that is always aligned to what is in latest Pharo.
That will simplify harvesting, merging, and everything. I wrote that somewhere but I don't remember.

**Comment by estebanlm** [comment]
we have a tag that is already aligned (which is more or less the same as a branch). 
but the commitish is required to pre-add the projects, and that I would like to fix somehow :(

**Comment by estebanlm** [comment]
this is fixed here: https://github.com/pharo-project/pharo/pull/9049
