### ISSUE TITLE
SpLabelled* widgets API and implementation should be revisited.

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#1023]

**Comment by Ducasse** [comment]
See https://github.com/pharo-project/pharo/pull/8926 for an attempt.

**Comment by Ducasse** [comment]
There are several points to check 

## The API ie. 

- `whenSelectionIndexChanged:`  should be called `whenSelectionIndexChangedDo:`

## The implementation

```
SpLabelledDropList >> whenSelectionIndexChanged: aBlock [
     self dropList whenSelectionIndexChanged: aBlock
```

vs.
 
```
SpLabelledDropList >> whenSelectionIndexChanged: aBlock [
     self dropList whenSelectionChangedDo: [:selectionMode | aBlock value: selectionMode selectedIndex]
```

## The API do we expose or not index based API.

**Comment by Ducasse** [comment]
Apparently we should remove the SpLabelled widgets.

**Comment by estebanlm** [comment]
they were moved to deprecated status
