### ISSUE TITLE
Issue harvesting from Pharo should be a bit clearer

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#1024]
It seems bug fixes are being overwritten https://github.com/pharo-project/pharo/issues/8886
And that they are causing differences that are not clear how to manage (at least to me) https://github.com/pharo-spec/Spec/pull/1021

**Comment by estebanlm** [comment]
yeah, I am not harvesting :)
Not many people touches Spec2, and since my times are very limited I expect people to do PRs here, to easy my work a bit Otherwise, it becomes quick a nightmare... also I think is educative ;)
