### ISSUE TITLE
Spec Examples: window title becomes "Message Browser"

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#1048]
Scenario:
 - go to "Help" -> "Spec2 examples"
 - the title of the window is "Spec UI Framework Demo"

![image](https://user-images.githubusercontent.com/5980033/115668909-f9918080-a347-11eb-96b5-20d1c7039957.png)

- Now click on "Notebook"
- the title of the window is changed into "Message Browser [468]"

**Now the title stays the same forever ("Message Browser [468]") when switching to another example and does not revert back into "Spec UI Framework Demo"** 

![image](https://user-images.githubusercontent.com/5980033/115669032-1fb72080-a348-11eb-9bf2-3cc4b2a4d2d6.png)

**Comment by estebanlm** [comment]
fixed upstream
