### ISSUE TITLE
Naming: Labeled instead of Labelled

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#1059]
In Spec2 examples:

![image](https://user-images.githubusercontent.com/5980033/116620198-ce0f2700-a941-11eb-8b65-e14ba62ab14f.png)

Both can be used: "labeled" and "labelled".

But "Labeled" is more commonly used in IT:
 - https://en.wikipedia.org/wiki/Labeled_data
 - https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Labeled.html
 - ...

**Comment by eftomi** [comment]
In software, American English is typically preferred, which suggests labeled.

**Comment by estebanlm** [comment]
afaik, I removed Labelled* presenters. What am I missing?

**Comment by astares** [comment]
Thanks!
