### ISSUE TITLE
SpTextPresenter>>text: memory leak.

### ISSUE THREAD

**Issue by kgardas** [pharo-spec/Spec#1068]
There is a memory leak somewhere in Pharo's VM or spec implementation. It's probably SpObservableSlot related. It's easily duplicated by:
```
tt := SpTextPresenter new.
tt openWithSpec.
1 to: 1000000 do: [ :n | tt text: (n asString,' test of line.') ].
```
It's probably slot related since if I try:
```
1 to: 1000000 do: [ :n | tt acceptText: (n asString,' test of line.').
            tt notifyPropertyChanged: #text. ].
```
it shows the memleak, but if I remove notifyPropertyChanged call, then memory leak is gone.

**Comment by estebanlm** [comment]
so, I have been looking at this... why do you say there is a "memory leak"?
I executed your test and observed the memory without seeing an increment of it that would show the leak... 
So now I am lost :)

**Comment by astares** [comment]
@kgardas Please try in a fresh image - be aware that Spec now uses ObservableSlot.

SpObservableSlot should have no users anymore.

**Comment by kgardas** [comment]
@estebanlm @astares Guys, please easy on me. :-) What I see or saw while reporting the issue was increasing RAM usage of the Pharo VM. Concretely with example above I'm able to go from 138MB RES to more than 490MB RES. The memory stays there even after code is finished and even after I execute `Smalltalk garbageCollect` -- so that's the reason I called that "memleak".

Now, the test above was done on build 1310 64bit Linux VM. It's possible that the issue is already solved. Please allow me to test on newest build and if it's solved there I may go for witch hunt and binary search the "hero" build which solved the issue. Thanks for your fast and very kind support!

**Comment by kgardas** [comment]
I've obtained todays' most recent 64bit Linux build number 1484 and drum rolls, the memory leak as described is still there. I'm using exactly this code:
```
tt := SpTextPresenter new.
tt openWithSpec.
1 to: 1000000 do: [ :n | tt text: (n asString,' test of line.') ].
```
just put that into playground, selected whole and right-click and select "Do It". Wait and wait and observe memory consumption growing of this particular VM in separate terminal window in htop -- in my case.

Please allow the code to run -- here it seems to run for several minutes till it opens text presenter window -- at this time whole memory leak should be visible.

Please let me know if you are able to duplicate or not. btw, running this on up-to-date Ubuntu 20.04.x LTS if that matters. FYI: RAM in this particular case go from 106MB till 488MB where it stayed.

**Comment by kgardas** [comment]
Guys, I've also duplicated memory leak on 64bit build 1488 running on Windows 10. So this is not platform specific (like glibc issue on linux). I hope you will be able to duplicate that too. Thanks! In case of Windows 10 the testing code enforce RAM consumption of VM to grow from ~128MB to 488MB.

**Comment by estebanlm** [comment]
yes, this has nothing to do with the vm. As long as we have found, it has something to do with ObservableSlots and spec adapters.

**Comment by kgardas** [comment]
Great! So does it mean you are able to duplicate and see the bug in action? Would be great to know. Thanks!

**Comment by estebanlm** [comment]
as I said, I cannot reproduce it anymore... can you download latest image and verify?

**Comment by kgardas** [comment]
Still duplicable on build 1497. Not sure if this is in or not yet.

**Comment by estebanlm** [comment]
![image](https://user-images.githubusercontent.com/513630/123252703-dec8bd00-d4ec-11eb-9b8c-9bc37147e602.png)

is in, and as you can see it is not reproducible for me (test started with image in 259m... now is 262m :/

**Comment by kgardas** [comment]
@estebanlm that's or would be fantastic result, but it's not yet in build 1497 which is the latest I see in pharo launcher. Either there is delay somewhere or I don't know. But you seems to be using Linux too I guess.

**Comment by kgardas** [comment]
@estebanlm my way of duplication is:
- run pharo launcher
- in _1. Choose a template category:_ select _Pharo 9.0 (development version)_
- in _2.Choose a template:_ select Pharo9.0-SNAPSHOT.build1497.sha.99cb401.arch.64bit
- click on _Create image_ button
- run the created image, copy code there into Playground and see the mem leak..

That is the most recent build I see here and this is the build I'm using for verification today.

**Comment by estebanlm** [comment]
yes, it is still the same, and I still cannot reproduce it.
Did you check the build is the right one (1497) ?(in Help/About...)

**Comment by kgardas** [comment]
Yes, in Help/About I see :
```
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1497.sha.99cb401855a6f011b3ae2b1950d5964545f6c68a (64 Bit)
```
also I'm verifying that for example: https://github.com/pharo-spec/Spec/pull/1105/commits/af258d23c2117abeebf9b737a63226f36da79ef2 -- is really presented in the VM image code. So sigh your code is indeed in, but I don't know what to do now since the mem leak is still here.

**Comment by kgardas** [comment]
```
 704M  563M 13892 S  1.3  0.4 37:27.04 /export/home/karel/Pharo/vms/90-x64/lib/pharo/5.0-202002121043/pharo /export/home/karel/Pharo/images/Ph
 651M  531M  8384 S  0.6  0.4 29:11.21 /export/home/karel/Pharo/vms/90-x64/lib/pharo/5.0-202002121043/pharo /export/home/karel/Pharo/images/Ph
 274M  151M  8504 S  1.3  0.1 36:59.15 /export/home/karel/sfw/pharo-launcher/pharolauncher/pharo-vm/lib/pharo/5.0-202002121043/pharo --plugins
```
the first image in the list is this one tested with memory leak. I can run the test several times here no problem and see where it's going to grow.

**Comment by kgardas** [comment]
I've also tested on Windows 10, build 1497 and the memory leak is there too.
[![st-memleak1.png](https://i.postimg.cc/ZYQXkmM3/st-memleak1.png)](https://postimg.cc/LhzxfcR6)

**Comment by estebanlm** [comment]
Ok, I tested this problem happens just in windows, but happens also using the morph directly (without spec in the middle). 
Which means this is not a Spec problem but a general one. 
@tesonep has the opinion this is because of freetype. 
This is the snippet to test with the morph: 
```Smalltalk
m := SpRubScrolledTextMorph new.
m openInWindow.
1 to: 1000000 do: [ :n | m setText: (n asString,' test of line.') ].
```

**Comment by kgardas** [comment]
@estebanlm the issue does not happen only on Windows. I told, my main platform is Linux and I do not know why it does not show also on your side. Do you use classical Spec or do you solely use its gtk-based derivative? Sorry if I'm putting this wrongly. But I use classical distro here...

**Comment by estebanlm** [comment]
I use mainly the morphic backend (which is where I did the test).
Mmmm... now I am lost :)

**Comment by kgardas** [comment]
Hmm, I'm lost too :-)

**Comment by estebanlm** [comment]
with freetype deactivated bug is there too :(

**Comment by kgardas** [comment]
@estebanlm by any chance, do you have anything in your working tree which miraculously fixes the issue? E.g. you are not able to duplicate that on Linux and this give me a hope... :-)

**Comment by estebanlm** [comment]
I just got to reproduce the problem in linux... I got suspicious and turns out the activity monitor is not refreshing correctly (it was mapping the wrong memory column). Now I am relieved, since is better a bug in all platforms than just one :)
Still, I have no idea what's the problem, but at least it happens everywhere.

**Comment by kgardas** [comment]
Cool! it's indeed a relieve to see it also happening on your side. Good! And thanks for confirmation!

**Comment by estebanlm** [comment]
so... not a leak.
In fact, this is the undo manager which is keeping all text changes.

**Comment by estebanlm** [comment]
now, question is... do setting manually the content of the text area should record change in the undo manager?

**Comment by kgardas** [comment]
Oops! That's one was unexpected. :-) Anyway, if this is the case I'm not against it, but I would also expect some API to set text w/o recording undo manager data here.
Imagine my case: SpTextPresenter is pretty low level text presenter (no rich text etc.) and I use that for logging server messages into UI. Single line of log is logged (set text) here and there is a lot of logs (setting) and definitely no undo needed here. How to do that?

**Comment by kgardas** [comment]
btw, for my application I don't need undo manager at all. Is there any simple way how to completely disable it VM/system wise? That may also be a way from this for me. Thanks!

**Comment by kgardas** [comment]
It looks like `clearUndoManager` is the method I've been looking for. So far testing on various builds and Linux/Windows platforms and the test code does not show memory leak at all. Big thanks to @estebanlm for kicking me to the right direction! :-)

Now, the question remains how to make that not happen for more casual devs like myself. Perhaps a clear comment would suffice? And perhaps remove of TODO remove in clearUndoManager and keeping that method where it is? Not sure what's the plan here and wouldn't like to step on another tiptoes here. :-)

**Comment by estebanlm** [comment]
no is not :)
that will help, of course... but wait a bit I will provide a way to disable it and a better way to handle it.

**Comment by estebanlm** [comment]
after this is integrated, you just set your presenter with `withoutUndoRedoHistory` and that will do the trick.

**Comment by kgardas** [comment]
@estebanlm Cool! This is indeed great! Thanks a lot for all your support on this issue!
