### ISSUE TITLE
The Pharo image breaks when trying to add spec local repository

### ISSUE THREAD

**Issue by jordanmontt** [pharo-spec/Spec#1072]
Steps to reproduce:
- Open Iceberg and select pharo-spec2 repository
- Load your fork (even with the upstream) 
- Select 'Discard image changes and load repository version'
Now you are not able to open any tool (like Playground, System Browser, Iceberg...) and an error message appears.
![image](https://user-images.githubusercontent.com/33934979/118549507-16548480-b74b-11eb-99df-cecdf212f4ab.png)

**Comment by estebanlm** [comment]
will be fixed when next merge happens
