### ISSUE TITLE
Rename SpecLayout to SpecTableLayout

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#108]
If we remove SpecTableLayout (See issue #106) maybe we can rename SpecLayout to SpecTableLayout since it's a layout managing columns and rows?

If we do it we should keep a deprecated subclass called SpetLayout for backward compatibility.

**Comment by pavel-krivanek** [comment]
will not be SpecLayout a general abstract class for all the layouts? That may make deprecation harder

**Comment by pavel-krivanek** [comment]
we will use AbstractSpecLayout for that

**Comment by jecisc** [comment]
SpecLayout will be removed. No need to work more on it.
