### ISSUE TITLE
SpPresenter>>request:initialAnswer:title: issues.

### ISSUE THREAD

**Issue by kgardas** [pharo-spec/Spec#1087]
Hi,
I've update from 9.0 build 1411 to build 1452 and my usage of:
`self request: 'Enter:' initialAnswer: '' title: 'Add something...'.`
stopped working. The method is using `message:` method which is no longer available and also `isOk' which is already done by openModalWithSpec.

**Comment by kgardas** [comment]
Looks like this is the patch responsible for breakage: https://github.com/pharo-spec/Spec/commit/dde97cbd72030c97d5d22b8823a110f430b0a3e4#diff-9e43d65dc6043143eac2c0e808c4f01604a6124c1dfddb55683db26bbca4325d

**Comment by kgardas** [comment]
@estebanlm do you plan to fix this breakage? Thanks!

**Comment by estebanlm** [comment]
uh? why the question? sounds a bit harsh :P 
yes, I implemented something that may have break that, I will look at fix it.

**Comment by estebanlm** [comment]
voilà :)
it will be in next image build

**Comment by kgardas** [comment]
@estebanlm sorry, not native English speaker and sometimes my writing is more terse than it should be. My aim was asking and since I know you are super busy with whole spec/pharo beast and you may not find the particular breakage that important, I may step in and try mu beginner luck on this one.
That was my intention, I'm sorry original question sounded that harsh... Thanks a lot for all your excellent work!

**Comment by estebanlm** [comment]
:)  is fine. 
Anyway... fix is coming :)

**Comment by kgardas** [comment]
Great! Thanks a lot for the fix, I'll test next snapshot and verify actually everything is all right and then close the issue. Thanks!

**Comment by estebanlm** [comment]
nah, do not worry, issue will be closed by itself :P
(the magic of github ;) )
