### ISSUE TITLE
Unused code: SpSourceStyler>>#applyStyleTo:inContext:

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#1092]
I guess the class **SpSourceStyler**:
 - is intended as common superclass with a concrete subclass
 - it should implement #isAbstract to return true
 - should provide an applyStyle... method with a subclassResponsibility or fulfill SpTextStyler>>#applyStyleTo:

and then SpSourceStyler>>#applyStyleTo:inContext: could be deleted (or used if a context is required)

Looks like WIP

**Comment by estebanlm** [comment]
it is WIP. I will put it in a separated package (all the SpRichTextPresenter) and we'll see later when I have time :(

**Comment by estebanlm** [comment]
fixed in 7c32ccb37c2f0ddcacf41084aa29deee6223232b
