### ISSUE TITLE
window properties of a presenter are inconsistent

### ISSUE THREAD

**Issue by estebanlm** [pharo-spec/Spec#113]
There are properties that are meant to define windows when the presenters are opened in one. 
- #title
- #initialExtent
- ?

I added the vocabulary `#prepareWindow:` to define how the window will open in case of need. 
But now I think there is an inconsistency between this two worlds.
I wonder if we shouldn't transfer this "window handling" properties to `#prepareWindow:` and take the opportunity to clean a bit `ComposablePresenter` ?

**Comment by jecisc** [comment]
Done.
