### ISSUE TITLE
SpNotebookPresenter probable memory leak.

### ISSUE THREAD

**Issue by kgardas** [pharo-spec/Spec#1144]
Hi,
I'm here on Pharo 9 build 1546 64bit on Linux. I'm trying to debug memory leaks in our software and based on this simplify to provide as simple as possible test cases for duplication. Code below when run in Playground and left running is able to show nice memory leak which is not able to solve by `Smalltalk garbageCollect` call. It's possible to "resolve" it by exiting and starting VM again -- so my bet would be the memory is held in some temporary data structures like undo buffers etc. Like it was case in the past in #1068 ? -- anyway, completely out of my idea how to solve this on my own hence reporting here.

```
notebook := SpNotebookPresenter new.
win := notebook openWithSpec.

text:=SpTextPresenter new.
text text: 'What about this?'.
text editable: false.
text withoutUndoRedoHistory.

notebook addPage: (SpNotebookPage title: 'Info' provider: [ text yourself. ] );
  selectPageIndex: 1.

stream := String new writeStream.
stream nextPutAll: 'The first sentence of our just a little bit longer text.';
  nextPut: (Character cr);
  nextPutAll: 'Second sentence which is a bit shorter.';
  nextPut: (Character cr);
  nextPutAll: 'And finally number provided by the loop construct is: '.

[ [  :job | job title: 'Running.'.
                job max: 1000000.
                1 to: 1000000 do: [ :n|
                        job progress: (n * 0.000001).
								UIManager default defer: [ 
									text text: (stream contents,n asString).
									notebook resetAllPageContents.
									].
								(Delay forMilliseconds: 10) wait.
                        ].
        ] asJob run ] fork.

```

Code comments:
- delay is there to give UI thread a chance to update. More or less work. If not, just increase delay -- or decrease it depends on you
- UIManager default defer -- this is self application defer in my code, but this does not work in Playground hence usage of UIManager default here
- text, you can use shorter and memory leak will not grow that fast. You can use bigger and it'll be more noticable.

Still Smalltalk beginner here so if I did horible mistake here please just comment and I'll fix based on your input quickly :-)

Thanks for any idea how to solve this!

**Comment by estebanlm** [comment]
hi, I just executed your code... I do not think this is a real problem. 
Yes, when objects become too big or remain too much time around, they are moved from "young space" to "old space" in memory, and they will not be collected until the VM performs a compact (which happens when you save the image, for example). 
If the problem that you have fades when you save the image, then I would say is not really a problem, but maybe the way you are using the component  makes it grow a lot in memory, and then takes time to go away?

**Comment by kgardas** [comment]
@estebanlm made really a good suggestion to investigate more about Pharo VM memory usage. Let's see modified code which prints full vm stats into the notebook -- hit two flies with one hit.
```
notebook := SpNotebookPresenter new.
win := notebook openWithSpec.

text:=SpTextPresenter new.
text text: 'What about this?'.
text editable: false.
text withoutUndoRedoHistory.

notebook addPage: (SpNotebookPage title: 'Info' provider: [ text yourself. ] );
  selectPageIndex: 1.

stream := String new writeStream.
stream nextPutAll: (Smalltalk vm statisticsReport);
  nextPutAll: 'And finally number provided by the loop construct is: '.

[ [  :job | job title: 'Running.'.
                job max: 1000000.
                1 to: 1000000 do: [ :n|
                        job progress: (n * 0.000001).
								UIManager default defer: [ 
									(n \\ 100) = 0 ifTrue: [ 
										stream := String new writeStream.
										stream nextPutAll: (Smalltalk vm statisticsReport);
										  nextPutAll: 'And finally number provided by the loop construct is: '.
										].
									text text: (stream contents,n asString).
									notebook resetAllPageContents.
									].
								(Delay forMilliseconds: 10) wait.
                        ].
        ] asJob run ] fork.


```
I'm providing the code now, but I'll comment behavior later after doing some experiments with this. Thanks for the hint!

**Comment by kgardas** [comment]
So I improved my testing code a bit (see below) and now I'm able to collect more scientific data which I'd like to present and claim this is indeed a memory leak. It also proves that in original claim that restart clears memory leak I was wrong. It (restart) does not clear it and memory leak is persistent over quit+save/restart cycle(s).

Iteraction | Memory | Old | Young | Used | Free
-------------|-------------|------|----------|---------|--------
1 | 121 | 98 | 6 | 76 | 28
2 | 421 | 398 | 10 | 384 | 24
3 | 721 | 698 | 12 | 687 | 23
4 | 1,021 | 998 | 9 | 981 | 25
5 | 1.321 | 1,298 | 9 | 1,281 | 26
6 | 1,623 | 1,600 | 9 | 1,581 | 28
7 | 1,920 | 1,897 | 9 | 1,880 | 26

Where iteraction is basically start pharo, run `Smalltalk vm statisticsReport` save data from it (screenshot), run the code, close the window open by the code to clears its memory, save+quit.
All numbers are numbers reported by `Smalltalk vm statisticsReport` divided by 10^6.

Since number of interaction in the testing program inner loop is 10k and we're leaking approximately 300MB per test iteraction this means single SpNotebook update (SpText update) leaks about 30kB of RAM.

Here is my latest testing code. It runs around 20 minutes on W-2265 so anybody is welcome to duplicate and confirm my findings.
```
notebook := SpNotebookPresenter new.
win := notebook openWithSpec.

text:=SpTextPresenter new.
text text: 'What about this?'.
text editable: false.
text withoutUndoRedoHistory.

notebook addPage: (SpNotebookPage title: 'Info' provider: [ text yourself. ] );
  selectPageIndex: 1.

stream := String new writeStream.
stream nextPutAll: (Smalltalk vm statisticsReport);
  nextPut: (Character cr);
  nextPutAll: 'And finally number provided by the loop construct is: '.

[ [  :job | job title: 'Running.'.
                job max: 10000.
                1 to: 10000 do: [ :n|
                        job progress: (n * 0.0001).
								UIManager default defer: [ 
									(n \\ 100) = 0 ifTrue: [ 
										Smalltalk garbageCollect.
										stream := String new writeStream.
										stream nextPutAll: (Smalltalk vm statisticsReport);
										  nextPut: (Character cr);
										  nextPutAll: 'And finally number provided by the loop construct is: '.
										].
									text text: (stream contents,n asString).
									notebook resetAllPageContents.
									].
								(Delay forMilliseconds: 100) wait.
                        ].
        ] asJob run ] fork.
	
```

Looking forward for your comment about it. Thanks a lot!

**Comment by kgardas** [comment]
When investigating it, I've got an idea to look into the saved image file and grep it for the text I'm using in the code above. See:
```
$ strings Pharo9.0-b1546-memleak-test6.image |grep "And finally number provided by the loop construct is"|wc -l
120098
```
and this is just a proof, I verified number of occurrences and this is indeed whole text I put into text: call. What's surprising is that it's 120k there while I would expect only 7 * 10k or so (or 2x 7*10k)...
Anyway, this is the leak. The data and associated objects should not be in the image...Smoking gun here...IMHO!

**Comment by Ducasse** [comment]
Thanks a lot for your analysis!!!! It is really great and definitively helps us!
tx tx tx

**Comment by kgardas** [comment]
I continue my analysis of this issue. I may be doing that thanks to help of 'astares' on Pharo discord vm channel. So using adviced allInstances and pointersTo methods I'm able to:
- find all ByteString instances (ByteString allInstances inspect)
- look into those, find representation of my text set in history -- e.g. instance which should be already GCed
- find all pointersTo it -> 1 Text instance
- find all pointersTo it -> 1 RubTextComposer instance
- find all pointersTo it -> 1 RubParagraph instance
- find all pointersTo it -> 1 RubOpeningClosingDelimiterDecorator instance
- find all pointersTo it -> 1 RubExtraSelectionDecorator instance
- find all pointersTo it -> 1 RubCurrentLineBarDecorator instance
- find all pointersTo it -> 1 RubEditingArea instance
- find all pointersTo it -> and here it looks like we're hitting the issue. It found 11 different objects: Array, RubTextEditor, RubEditingState, RubPlainTextMode, RubCursor, RubPrimarySelectionMorph, KMDispatcher, RubParagraph, KMTarget, KMCategoryBinding, KMCategoryBinding.
Issue is that complexity bubles up to level man can't do that by hand. E.g. far I've done this up to here by using:
```
(((((((((ByteString allInstances at: 57405) pointersTo at: 1) pointersTo at: 1) pointersTo at: 1) pointersTo at: 1) pointersTo at: 1) pointersTo at: 1) pointersTo at: 1) pointersTo inspect
```

So I think it is a time to start from reverse direction, from Smalltalk by using ReferenceFinder tool.
```
(ReferenceFinder findAllPathsTo: (ByteString allInstances at: 57405)) inspect
```
and the returned result is empty sequence.
This is IMHO strange since if Smalltalk object cannot navigate to this specific ByteString object than I'm curious how Smalltalk's garbage collector may find it. IMHO strange.
If anybody does have any explanation for this, I would really appreciate it.

**Comment by kgardas** [comment]
Just for the record, based on `Stepharo` ask on #spec channel on Pharo's discord I've also tested latest Pharo 10 build (127) and I was also able to duplicate memory leak behavior there. What's interesting is that I've been able to use ReferenceFinder to find real path from Smalltalk to what should already be GCed ByteString object. Maybe I was just lucky and in case of Pharo9 above unlucky? Will probably test.

**Comment by Ducasse** [comment]
Thanks for this analysis. Memory leaks are always a pain.

**Comment by estebanlm** [comment]
a heads up of this: I spent last two days hunting the leak and actually found a bigger leak that your notebook example exposed (leak is in SpTextPresenter but not just there...).
So I am polishing a solution and next days (monday or tuesday) I will be submitting the fix along with a backport to Pharo 9.

**Comment by kgardas** [comment]
@estebanlm thanks a lot for working on this one. Honestly I've thought SpTextPresenter memory leak on `text:` call is well behind us thanks to your fixes on it. Anyway, JFYI I
m not using SpNotebookPresenter only with the SpTextPresenter -- this was just as simple as possible example to duplicate the issue. As one or two pages I'm also using Roassal3 diagrams which are redrawn on the update. Those cases memory leak too, but one step after another first. :-)

Anyway, thanks a lot for working on that one!

**Comment by estebanlm** [comment]
Problem is not the set of text, it has to do with registering of announcers and rebuilding of backend elements. 
It happens in every component that uses this mechanism (and it will be visible in the notebook since it rebuilds components)

**Comment by kgardas** [comment]
@estebanlm thanks for explanation! So all those Rub* objects are backends and relicts of setting new text right. Cool, I'm glad I've not stepped on a side with this one.

**Comment by estebanlm** [comment]
this should be now fixed, both on Pharo 10 and  backported to Pharo 9.0 :)

**Comment by demarey** [comment]
@estebanlm could you add a link to the fix ?

**Comment by kgardas** [comment]
I've tested on 9.0 build 1552 and 10.0 build 155 and indeed memory leak is gone. Thanks a lot @estebanlm for fixing that!
