### ISSUE TITLE
SpDropListPresenter error when items: size reduces (SpDropListMorph error)

### ISSUE THREAD

**Issue by Whalehead99** [pharo-spec/Spec#1145]
SpDropDownError is to demonstrate an error where the items set changes (is reset).

What am I trying to accomplish?
- I have a list of items.  I have a dropDown list where one of these items can be selected and an operation can be performed... delete, move to another list, duplicate, etc. 
- Anything that doesn't reduce the items count (duplicate, update, etc.) - the error does not appear and the highlight is on the proper row (selectItem: object1, for instance)
- If we reduce the items size (move or delete), when the last item selected was any index# higher than the new items size, we get the Morph error stack.

Notes/How to use:
- I've included an SpTablePresenter of the same orderedCollection - just for visual - it has no impact
- 3 buttons - Exit (redundant, but my popups are usually modal), Reset - reset the collection to threeelements, Delete - delete the item selected in the dropDown list... the item selected in the tablePresenter is irrelevant. 
- checkbox - both activate and deactivate call refreshPresenters which reload the current collection into items: for both the tablePresenter and dropListPresenter.

Observables:
- an items collection of say 3 objects, and the 3rd object was highlighted in the SpDropList (either by physical selection or by selectItem: 3rdObject).
- if we remove that object, or simply replace the items with a collection of < 3 objects...
	- by placing breaks in the code, we can see SpDropList contains the new collection AND visibly selects a desired object... ie.  selectItem: object1.
- however, an error is generated (with a relatively short stack of debug records) - SpDropListMorph seems to be holding on to the index# of the previous collection as the error is that it can't selectIndex: anInteger - where anInteger is 3.
	
I've tried >>selectItem: object1,  >>resetSelection.  Neither appear to change behavior.

The error is masked if the new items list is the same or great size than the original.

When the last element is removed, the error reappears as the items collection is empty, and SpDropListMorph is trying to selectIndex: 1.

Attached files - SpDropListError.txt (rename to .st and fileIn), and a screen shot of the error stack.

Once filed in, run example on the class side.
[SpDropDownError.txt](https://github.com/pharo-spec/Spec/files/7131563/SpDropDownError.txt)
![Screen Shot 2021-09-08 at 2 29 24 PM](https://user-images.githubusercontent.com/60747610/132578888-244a7b8a-448d-4ed4-8ad7-2af2a1daa803.png)

**Comment by jordanmontt** [comment]
Related to #944

**Comment by estebanlm** [comment]
Fixed along with https://github.com/pharo-spec/Spec/issues/944
