### ISSUE TITLE
[Cleanup] remove pool var related code from SpCodePresenter

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/Spec#1151]
Somehow I can not commit are removal of these methods (changing the sender to not call them worked and was already merged)

SpCodePresenter>>#browseImplementorOfPoolVar
SpCodePresenter>>#browsePoolVarNode:

TODO: remove these methods, deprecation not needed

**Comment by astares** [comment]
You cannot commit removes of these methods?
I can not commit a removed classInstVar - see issue #10015 in pharo-project

**Comment by MarcusDenker** [comment]
My problem seems to be that the way I setup my Newtools/spec repos for commiting, it is not in sync with the code in the image.
(if I commit, it wants to commit a lot of code, I think the verision it thinks it has does not have these methods, so it can not commit a removal)

**Comment by MarcusDenker** [comment]
This is fixed
