### ISSUE TITLE
SpDemo freezes the image (under some conditions)

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#1161]
# how to reproduce
- take latest Ph10
- use the menu to see the example

You image is killed.

**Comment by estebanlm** [comment]
which example?

**Comment by estebanlm** [comment]
ping @Ducasse, which test ?
I cannot reproduce it opening the SpDemo, so... no idea what you are talking about.

**Comment by estebanlm** [comment]
I will need a way to reproduce this :(

**Comment by Ducasse** [comment]
Yes I could do it several so I thought it was reproducible so let us close it
