### ISSUE TITLE
beNotEditable does not work in SpTextInputFieldPresenter

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#1162]
```
SycMethodNameEditorPresenter >> 
initializeWidgets
	selectorInput := self newTextInput.
	argumentsList := self newList.
	previewResult := self newLabel.
	upButton := self newButton.
	downButton := self newButton.
	addButton := self newButton.
	
	selectorInput autoAccept: true.
	upButton label: 'Up'.
	downButton label: 'Dn'.
	addButton label: '+'.
	selectorInput text: methodName selector.
	previewResult label: methodName methodName.
	
	self setFocus
```

Change it to 

```
SycMethodNameEditorPresenter >> 
initializeWidgets
	selectorInput := self newTextInput.
        selectorInput beNotEditable. 
	argumentsList := self newList.
	previewResult := self newLabel.
	upButton := self newButton.
	downButton := self newButton.
	addButton := self newButton.
	
	selectorInput autoAccept: true.
	upButton label: 'Up'.
	downButton label: 'Dn'.
	addButton label: '+'.
	selectorInput text: methodName selector.
	previewResult label: methodName methodName.
	
	self setFocus
```

- Open the SycMethodNameEditorPresenter and the selectorInput field is still editable while it should be read-only.
-

**Comment by Ducasse** [comment]
I thought that I made a mistake in this class. 
So I did a minimal test and noEditable does not work.

**Comment by Ducasse** [comment]
[SpTryPresenter.txt](https://github.com/pharo-spec/Spec/files/7288676/SpTryPresenter.txt)


'From Pharo10.0.0 of 1 October 2021 [Build information: Pharo-10.0.0+build.173.sha.e8c837e85e5ac6db6403d4de88a4a32682e8b5a5 (64 Bit)] on 5 October 2021 at 9:18:38.306599 pm'!
SpPresenter subclass: #SpTryPresenter
	instanceVariableNames: 'selectorInput'
	classVariableNames: ''
	package: 'SpTry'!

!SpTryPresenter methodsFor: 'initialization' stamp: 'sd 10/5/2021 21:13'!
selectorInput
	^ selectorInput! !

!SpTryPresenter methodsFor: 'initialization' stamp: 'sd 10/5/2021 21:13'!
selectorInput: agr
	selectorInput := agr! !

!SpTryPresenter methodsFor: 'initialization' stamp: 'sd 10/5/2021 21:12'!
initializeWidgets
	selectorInput := self newTextInput.
	selectorInput beNotEditable ! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

SpTryPresenter class
	instanceVariableNames: ''!

!SpTryPresenter class methodsFor: 'specs' stamp: 'sd 10/5/2021 21:17'!
defaultSpec 
	<spec>
	^ SpBoxLayout newTopToBottom
		add: #selectorInput;
		yourself! !

**Comment by Ducasse** [comment]
<img width="669" alt="Capture 2021-10-05 at 21 05 17" src="https://user-images.githubusercontent.com/432549/136088909-51ce38fc-3c72-4973-bef2-e231d8d8528f.png">

**Comment by Ducasse** [comment]
<img width="412" alt="Capture 2021-10-05 at 21 21 27" src="https://user-images.githubusercontent.com/432549/136089044-619f5f33-e6c4-4c0d-9b29-9510c0aa70e1.png">

**Comment by Ducasse** [comment]
I do not get it because the test testEditable is green. 

```
testEditable

	presenter beNotEditable.
	self openInstance.
	
	presenter adapter 
		keyDown: $x asciiValue
		shift: false 
		meta: false 
		control: false 
		option: false.
	
	self assert: presenter text equals: ''.
	
	presenter beEditable.
	
	presenter adapter 
		keyPressed: $x 
		shift: false 
		meta: false 
		control: false 
		option: false.
	
	self assert: presenter text equals: 'x'.
```

**Comment by estebanlm** [comment]
this are the easiest tests possibles: 

```Smalltalk
SpTextPresenter new 
	text: 'test';
	beNotEditable;
	openWithSpec.

SpTextInputFieldPresenter new 
	text: 'test';
	beNotEditable;
	openWithSpec.
```

I can confirm it works on Text, but not on TextInputField. Text for report.

**Comment by estebanlm** [comment]
also 
```Smalltalk
SpTextInputFieldPresenter new 
	text: 'test';
	openWithSpec;
	beNotEditable.
``` 
works, so is an initialization problem

**Comment by Ducasse** [comment]
Indeed this is simpler.
