### ISSUE TITLE
testClickDeactivatedCheckboxActivatesIt started to fail in integration tests

### ISSUE THREAD

**Issue by estebanlm** [pharo-spec/Spec#1164]

**Comment by estebanlm** [comment]
Well, after trying a lot, I finished disabling it in the CI.
Do you have an idea, @demarey ?
anyway, I hope it will be magically fixed in next versions ;)

**Comment by demarey** [comment]
No idea. The test is so simple that it should work. When should invest time to fix it.
Does it always fail now? Does it sometimes fails outside the CI?  
It could be a problem with the environment but we do not have the test output in the log. The best would be to try to reproduce this locally.

**Comment by estebanlm** [comment]
it fails consistently in CI *when running the complete set of pharo tests*, and it passes consistently in all other cases :(

**Comment by estebanlm** [comment]
ok, let's close this for the moment
