### ISSUE TITLE
Spec repository commitish is not in sync with what is really installed

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#1178]
See for example this diff, the version shown by iceberg is not what is in the image

![image](https://user-images.githubusercontent.com/708322/137877483-e34ae2cc-94cd-48e1-adb3-eb9106efe3f3.png)

To reproduce:
 - clone spec using a repair action
 - create a "branch from image commitish" using a repair action

And then we have a lot of differences!

![image](https://user-images.githubusercontent.com/708322/137878189-ea05d688-a5e3-48b4-a8e6-993a3b31269c.png)

This is very noisy at the least. And it is even worse:
 - from the commit information, I understand that in the repository we have the code that we want, so we do not need to solve #1156
 - but if we look at the latest branches in github, that code is not in the repository
 - then it is not clear if we should make a PR to solve https://github.com/pharo-spec/Spec/issues/1176?

**Comment by estebanlm** [comment]
in Pharo10, this is like that, yes... the commitish has no sense there (this is used for when we use a tagged version, like in release). I guess we can made something to fix it in those cases.
EDIT: but I don't know what, heh.

**Comment by MarcusDenker** [comment]
The problem is that I do not know how to contribute with the setup now... if I use the standard way, I get an image that is both way out of sync.... e.g. I tried to remove methods and I could not as the image thought they are not there.

**Comment by MarcusDenker** [comment]
after https://github.com/pharo-project/pharo/pull/10697, this now works fine!
