### ISSUE TITLE
Remove the shouldBeImplemented alert for defaultSpec on class side

### ISSUE THREAD

**Issue by jordanmontt** [pharo-spec/Spec#1187]
That alert appears when you don't implement the method `defaultSpec` on the class side of a presenter. As is no longer necessary, because you can initialize your presenters on the instance side, there is no need of the alert. 

![Capture d’écran 2021-10-22 à 16 41 44](https://user-images.githubusercontent.com/33934979/138475053-780e0b2d-8250-428f-9227-e6965fde3a70.png)

**Comment by Ducasse** [comment]
yes!!!
