### ISSUE TITLE
SpPresenter>>#removeStyle: and SpPresenter>>#addStyle: are not working properly

### ISSUE THREAD

**Issue by jordanmontt** [pharo-spec/Spec#1189]
Consider the following script

```st
presenter := SpPresenter new.
presenter application: (app := SpApplication new).

styleSheet := SpStyle defaultStyleSheet, 
	(SpStyleVariableSTONReader fromString: 
	'.application [
		Font { #bold: true },
		.lightGreen [ Draw { #color: #B3E6B5 } ],
		.bgBlack [ Draw { #backgroundColor: #black } ],
	   .blue [ Draw { #color: #blue } ]
]' ).

app styleSheet: styleSheet.

presenter layout: (SpBoxLayout newTopToBottom
	add: (label := presenter newLabel);
	yourself).

label label: 'I am a label'.
label addStyle: 'lightGreen'.
label addStyle: 'bgBlack'.
 
presenter openWithSpec.

label removeStyle: 'lightGreen'.
label removeStyle: 'bgBlack'.
label addStyle: 'blue'.
```

the styles `bgBlack` and `lightGreen` are not actually removed.

<img width="399" alt="Capture d’écran 2021-10-22 à 20 50 48" src="https://user-images.githubusercontent.com/33934979/138507948-a65f62b0-a994-488b-b6e1-50b80ba7f211.png">

**Comment by estebanlm** [comment]
hello,
this is in fact because you are not defining a "default" color, so when you remove the style, Spec does not know where to fallback. Take this corrected script: 

```Smalltalk
presenter := SpPresenter new.
presenter application: (app := SpApplication new).

styleSheet := SpStyle defaultStyleSheet, 
	(SpStyleVariableSTONReader fromString: 
	'.application [
		Font { #bold: true },
		Draw { #color: #white, #backgroundColor: #transparent },
		.lightGreen [ Draw { #color: #B3E6B5 } ],
		.bgBlack [ Draw { #backgroundColor: #black } ],
	   .blue [ Draw { #color: #blue } ]
]' ).

app styleSheet: styleSheet.

presenter layout: (SpBoxLayout newTopToBottom
	add: (label := presenter newLabel);
	yourself).

label label: 'I am a label'.
label addStyle: 'lightGreen'.
label addStyle: 'bgBlack'.
 
presenter openWithSpec.

label removeStyle: 'lightGreen'.
label removeStyle: 'bgBlack'.
label addStyle: 'blue'.
```

It will produce the expected result :)

**Comment by Ducasse** [comment]
Esteban is that line 
Draw { #color: #white, #backgroundColor: #transparent },
the default color?

**Comment by estebanlm** [comment]
yes, it is in top of the style so is taken as default (a little bit like a CSS, in this case).

**Comment by jordanmontt** [comment]
I thought that the default color was set "by default" in the default styles of the application.

**Comment by estebanlm** [comment]
what actually happens when you remove a style is that spec recalculates the resulting style an reapplies it, but this time without the one you already have. If you see, what you did here: 

```Smalltalk
app styleSheet: styleSheet.
```

it lacks the default stylesheet: 

```Smalltalk
app styleSheet: SpStyle defaultStyleSheet, styleSheet.
```

So there are no defaults defined :) 

Edit: But since removing dynamically a background was not something I thought as an scenario, I think the default background is not defined there either... :/ 
Edit 2: Oops. Is not true, you did added the default stylesheet. Which means it does not has the default background color defined, confirming what I said in the first edit :P
