### ISSUE TITLE
drop list items actions are triggered twice

### ISSUE THREAD

**Issue by demarey** [pharo-spec/Spec#1259]
When using a drop list presenter, and setting some action on its items, when clicking on item, the same action is triggered twice instead of only one time.
Here is an example to reproduce the pb:
```smalltalk
count := 0.
list := SpDropListPresenter new.
items := OrderedCollection new.
items addFirst: (SpDropListItem new
				model: 'Edit configurations ...';
				action: [ count := count + 1. count inspect ];
				yourself ).
list
	resetSelection; 
	dropListItems: items.
list open.
```

Then click on the element. You will see 2 inspectors popping.

The action is triggered twice by PluggableIconListMorph(Morph)>>#handleMouseDown:
- a first time on line 17
- a second time on line 26

**Comment by estebanlm** [comment]
You are using incorrect API. 
`dropListItems:` is private and should not be used publicly. 
Correct API would be something like this: 
```Smalltalk
count := 0.
list := SpDropListPresenter new.
list addItemLabeled: 'Test' do: [ count := count + 1 ].
list resetSelection.
list open.
```
(not using the private API).

Now, why this private API is failed (and why it exists)... no idea :p

**Comment by demarey** [comment]
ah, sorry I did not notice the use of a private API.
Here is an updated example that is still failing for the same reasons:
```smalltalk
count := 0.
SpDropListPresenter new
	addItemLabeled: 'Test' do: [count := count + 1. count inspect ];
	open.
```

**Comment by estebanlm** [comment]
that is not failing for me.
But I removed the inspect (that may or may not cause side effects ?).

**Comment by demarey** [comment]
> that is not failing for me. But I removed the inspect (that may or may not cause side effects ?).

I just tried on a fresh image and it fails. Did you select the item in the list?
Inspection has no side effect, you can remove it if you want.

**Comment by LABSARI** [comment]
I have a similar issue when i do this: 
`self newDropList
	startWithoutSelection;
	items: self fetchItems;
	whenSelectionChangedDo: [ :e | 1halt ];`

When I select an item in the drop list, the halt is triggered twice.

**Comment by estebanlm** [comment]
so, I was working on this. 
I cannot reproduce it, in fact. 
What *I did find* is that actually startWithoutSelection was not working, hence you will always have a first element selected, hence you will always have a first selection change called (which was also wrong, since the original status is not a selection change).
I am actually fixing that, in the hope this is the real issue we are talking about :)

**Comment by demarey** [comment]
@estebanlm I just tested the fix and it does not fix the current issue. Did you try with the code I provided?

**Comment by estebanlm** [comment]
yes, I tried, and I cannot get your problem :)

**Comment by estebanlm** [comment]
Okay... after a night digging. 
This is a problem on morphic, in concrete `ScrollPane>>mouseDown:` is processing the events defined in eventHandler property while `Morph>>handleMouseDown:` is doing it too. 
Then it happens twice. 
NOTE: `handleMouseDown:` is the correct one. 
This is a complicated fix that can impact all around the environment, hence we cannot fix it for P10 release, it will need to wait :(
