### ISSUE TITLE
Context menu not activated on empty tables

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#1277]
I  have a method like this:

```Smalltalk
initializePresenters
    packageList := self newTable.
    packageList items: self packages.
    packageList contextMenu: [ self packageListMenu ].

    self layout: (SpPanedLayout newTopToBottom
             add: (SpPanedLayout newLeftToRight
                      positionOfSlider: 0.3;
                      add: packageList;
                      ...
```

but the context menu opens only when there are items (packages in this case) available in the table.

But I would like to have a context menu already opened on an empty table so that the context menu can offer a "New package...." menu item

**Comment by astares** [comment]
@estebanlm wrote today on Discord:  

"That seems like a bug, a remaining from morphic So yes, it should be fixed"

**Comment by astares** [comment]
As I guess this is not an uncommon situation to use (initially empty) lists with context menus 
and we want Pharo users to be able to build UIs easily using Spec it would be nice if this 
could be fixed for an upcoming Spec iteration (Pharo 11??)

**Comment by astares** [comment]
As far as I can see the problem is that FTTableMorph>>mouseDown: is not handling the context menu click (right click or "yello button pressed" in Smalltalk terms.

Adding the following line seems to solve the problem:

![image](https://user-images.githubusercontent.com/5980033/174681295-312f1549-d256-4831-8e3a-ae927f5a2cdb.png)

**Comment by astares** [comment]
This is not an issue of Spec but an issue within FastTable (which is not part of Spec packages)

So I opened a regular bug for Pharo https://github.com/pharo-project/pharo/issues/11388 to fix it in standard image.

**Comment by estebanlm** [comment]
in fact, I will reopen here.
I can fix it here, and I do not want to introduce a possible regression outside this (I don't know how the context menu without selection would work on Calypso, for example).

**Comment by estebanlm** [comment]
Mmm... In fact I just tested and works even better ;)
I will fix both.

**Comment by estebanlm** [comment]
and of course there were drawbacks. 
but should be working, let's see.

**Comment by estebanlm** [comment]
okay this should be merged now
