### ISSUE TITLE
Can't fine ComposableModel class in my Pharo 10 image

### ISSUE THREAD

**Issue by lucretiomsp** [pharo-spec/Spec#1278]
I am trying to follow the booklet to learn Spec but at the very beginnin I find:
ComposableModel subclass: #CustomerSatisfaction
  instanceVariableNames: 'buttonHappy buttonNeutral buttonBad screen'
  classVariableNames: ''
  package: 'Spec-BuildUIWithSpec'

but there is no ComposableModel class in my Pharo 10 image.
what am I doing wrong?

**Comment by demarey** [comment]
Hi Domenico,

The booklet you take a look at is for Spec 1.
`ComposableModel` has been replaced by `SpPresenter` in Spec 2 (default in Pharo 10).
It is a work in progress but you can find a version for Spec2 here: https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/releases/download/latest/Spec2-wip.pdf

**Comment by BigProgramme** [comment]
Very helpful, thank you.

I've been find what I was looking for a days, thank you
