### ISSUE TITLE
Compatibility with Pharo9

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-spec/Spec#1280]
Hello, readme suggests Spec2 should be loadable into Pharo 10 and Pharo 9 with following script:
``` 
    Metacello new
        repository: 'github://pharo-spec/Spec:Pharo10';
        baseline: 'Spec2';
        onConflict: [ :e | e useIncoming ];
        onUpgrade: [ :e | e useIncoming ];
        ignoreImage;
        load
 ```
 
It works for Pharo 10, but when I use this script in Pharo 9, I get following warning:
![obrazek](https://user-images.githubusercontent.com/9571633/173352723-0868b3b9-1dbb-40d4-a4a7-f2030d5b1175.png)

Once I click proceed, loading finishes, but nothing works anymore. Cannot open System browser, Iceberg, not even debugger....
```
**Debugger opening error*
Original error: Instance of ClyNotebookPageHeaderPresenter did not understand newImage.
Debugger error: Instance of StRawInspection did not understand #build
```

I understand if loading current Spec2 into Pharo 9 would not be possible, then the fix is to edit the readme.

OS: Windows 10, Pharo 9.0.0 build 1575 out of commit 9bb5f99.

**Comment by estebanlm** [comment]
true, it is not P9 compatible anymore. I will remove that.

**Comment by estebanlm** [comment]
fixed in https://github.com/pharo-spec/Spec/commit/243839bf0324ba25ae04887efe0981b111120f2a
