### ISSUE TITLE
SpMethodToolbarPresenter is undeclared

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#1308]
Not sure that this is related to spec but we got the following error on the build.

```
Found undeclared Variables:  SpMethodToolbarPresenter in: AbstractMessageCentricBrowser>>#initializePresenters
Stacktrace

TestFailure
Found undeclared Variables: 
SpMethodToolbarPresenter in: AbstractMessageCentricBrowser>>#initializePresenters
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest>>testUndeclared
ReleaseTest(TestCase)>>performTest

```

**Comment by MarcusDenker** [comment]
I added an issue for the main tracker, too: https://github.com/pharo-project/pharo/issues/11670

(as it leads to failing tests on the CI)

**Comment by MarcusDenker** [comment]
this might be fixed already in Spec, but as the CI is down we do not get the latest code in Pharo11

**Comment by demarey** [comment]
no, it is not fixed.
It is introduced by 50513b969ffc5d1acdb795fb2880f5cd04a62940.
Now, SpMethodToolbarPresenter is part of NewTools (https://github.com/pharo-spec/NewTools/commit/54ef2125a6aec08e280c3d117cfa3e75f77e6bc6) but only in `dev-1.0` branch.
It should be merged in `Pharo11`branch

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-spec/NewTools/pull/417
