### ISSUE TITLE
Provide missing SpCommandGroup>>#asToolbarPresenter

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#1316]
Seaside Control panel is broken due to a missing method:
https://github.com/SeasideSt/Seaside/issues/1345

We need to provide missing SpCommandGroup>>#asToolbarPresenter

```Smalltalk
asToolbarPresenter
	^ SpToolbarPresenterBuilder new
		visit: self;
		toolbarPresenter
```

**Comment by jbrichau** [comment]
Any chance this will be included? Otherwise I apply @astares proposed change to Seaside code...

**Comment by Ducasse** [comment]
@estebanlm

**Comment by Ducasse** [comment]
I think that esteban change it and that it will not be added back but may be it was about something else.

**Comment by estebanlm** [comment]
yeah, that will not go back because it was a mistake (the builder would require to know the application where it is being executed, and it is not the case).
Seaside can just add back the method, if they want... or remove its usage (is easy)
