### ISSUE TITLE
Add a deprecation for openWithSpec to open

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#1326]
I was trying some old code (P9 or P10) and the code uses openWithSpec. 
Apparently now this is open. 
So we must use a proper deprecation from openWithSpec to open.

**Comment by demarey** [comment]
deprecation was present in P10, then it was removed in P11.

**Comment by Ducasse** [comment]
I do not get why. Yes to force people to go into P10. This is because Marcus does not like to see such methods accumulating but this is so cheap. In the past I spent times trying to package them to help people migrating but I stopped because massive loss of interest from my side. So we can close this issue and I do not care.

**Comment by demarey** [comment]
No, I removed them as usual process: deprecation in version n, removal in version n + 1.
Would you like to keep deprecations more than one version?

**Comment by Ducasse** [comment]
There are the deprecations that are boring because they keep back code around and the ones that cost nearly nothing and these could be kept around at least two versions.
