### ISSUE TITLE
SpStyleEnvironmentFontVariable>>#value: avoid symbol interning for the default case

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/Spec#1329]
SpStyleEnvironmentFontVariable>>#value leads to lots of sends to #asSymbol for the defaultFont

We could just hard code that:

```
value
	^ self name = 'default' 
		ifTrue: [ StandardFonts defaultFont ]
		ifFalse: [ StandardFonts perform: (self name, 'Font') asSymbol ]
```

**Comment by Ducasse** [comment]
Sorry but we should stop propagating globals so at least it should be 

```
value
	^ self name = 'default' 
		ifTrue: [ Fonts defaultFont ]
		ifFalse: [ Fonts perform: (self name, 'Font') asSymbol ]
```
and Fonts should be a classVariable initialized to StandardFonts for now.

**Comment by MarcusDenker** [comment]
My idea was to fix *one* thing: avoid interning the symbol. 

I propose to merge this and open another issue for the other, not related, improvement

**Comment by Ducasse** [comment]
ok for me now I do not see why adding one classvar and initialize method is super complex to do it now.

**Comment by MarcusDenker** [comment]
it is the same amount than merging this now and doing a second PR.

The good thing is that then my fix is not hold up by a completely unrelated improvement.

**Comment by MarcusDenker** [comment]
StandardFonts is not a global but a Class. I now so little about it to the point that I do not even understand what the problem is.

**Comment by Ducasse** [comment]
The problem is that in general we should not point to a global being a class or no like this. 
Because StandardFonts is like the old ugly Preferences class. 
People should not use if directly. A component should manage its customisation point and not refer to the class in a global manner. This is exactly what we work against when we introduced Settings.
