### ISSUE TITLE
Presenters should announce focus

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#1366]
Right now, the only way to know if the focus changed is to directly access the backend with something like:

```smalltalk
self withAdapterDo: [ 
			self adapter children second textArea announcer
				when: MorphGotFocus
				do: [  ... ] ].
```

It would be nice if such behaviour is encapsulated in a presenter method `whenFocusedDo:`

**Comment by estebanlm** [comment]
presenters already have that :)
just a bit hidden? 
we made the choice of not polluting the base presenter with events that may be used just on certain conditions. It may be a bad decision but is the one we have for now :)
(What is definitively needed is a better/updated comment for the SpPresenter class).

``` Smalltalk
aPresenter eventHandler whenFocusReceivedDo: [ :anEvent | ... ]
```

will do the trick :)

**Comment by Ducasse** [comment]
I added a section in the book tip and tricks and can you update the class comment?
