### ISSUE TITLE
Search should not be enable by default in ListPresenter

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-spec/Spec#139]
For now it is enabled by default.

**Comment by jecisc** [comment]
Esteban agrees

**Comment by jecisc** [comment]
Ok, this is really messy.

The ListPresenter has an API to set a filter, but it's used nowhere. 

The FastTablePresenter always has a substring filter.

I'm not sure we should even have a FastTablePresenter. Before correcting this issue I think I need to discuss with Esteban about what we really want to do with the lists.

**Comment by jecisc** [comment]
Done in list presenter.
