### ISSUE TITLE
Cannot use the slider with the mouse

### ISSUE THREAD

**Issue by labordep** [pharo-spec/Spec#1410]
As #899, the slider used in the Spec2 example cannot be used correctly with the mouse.
It is not possible to click directly on the bar, and when the slider is drag & drop the drop can not set the value and there is a graphic glitch during the drag.

![sliderBug](https://github.com/pharo-spec/Spec/assets/49183340/e7573b40-9acb-4b05-b227-343144e86e22)

The example is here : `SpDemoStandaloneFormPresenter`

My config : 
Pharo-11.0.0+build.692.sha.0c234f2f5a92b237dd22ef9429506e92e586c494 (64 Bit)
Windows 11 Pro x64

**Comment by astares** [comment]
Update: still relevant in Pharo 13

**Comment by tinchodias** [comment]
This is fixed after #1619 (for Morphic backend)

Thanks @astares I didn't realize this issue existed

**Comment by tinchodias** [comment]
It seems I don't have permissions to close the issue.

**Comment by astares** [comment]
Confirm it is fixed. I also do not have the permission to close issues here in Spec repo.

@estebanlm / @MarcusDenker 
Can you close this issue or give @tinchodias and me the permission to manage/close issues here as well.
