### ISSUE TITLE
SpMillerPresenter is very buggy when having more than 2 panels

### ISSUE THREAD

**Issue by jordanmontt** [pharo-spec/Spec#1441]
The Notebook presenter is very buggy when using the miller list with more than 2 elements. For example, look in the attached GIF, when putting 3 elements on the miller list a blank space appears at the right.

![1](https://github.com/pharo-spec/Spec/assets/33934979/4be78ad2-9910-4101-b199-ae27ba5ce9f2)

So one cannot navigate. It looks like is it made only to work with 2 panes. When you put 4 you ave 2 blank spaces

![2](https://github.com/pharo-spec/Spec/assets/33934979/2634e31e-ee7f-4053-94e1-31b752c0b438)

**Comment by estebanlm** [comment]
this should be fixed now
