### ISSUE TITLE
Provide a default #enable: method on ComposablePresenter

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-spec/Spec#145]
This method would recursively set `#enable:` value on sub-presenters.

**Comment by estebanlm** [comment]
yeah, problem with this is there is no way to know which sub presenters are present :)

**Comment by estebanlm** [comment]
I don't know if we can actually provide this, in fact (unless we add some introspection logic).

**Comment by jecisc** [comment]
Esteban did it.
