### ISSUE TITLE
Improve/change/kill the interpreter of Spec

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#15]
The current interpreter needs to be improved. Maybe we could get a new implementation.

**Comment by estebanlm** [comment]
do we really need an interpreter? 
I made an experiment to avoid the usage of it when delivering layouts (for a GridLayout I want to add) and it doesn't look an interpreter actually give us something valuable.

**Comment by jecisc** [comment]
The only value of the Interpreter is to be able to declare spec in an interactive way. 

Personally, I would like to kill it in the long term. But we need to re-implement the current layouts to do that and hope that not many people used the declarative way.

**Comment by estebanlm** [comment]
"current layouts" is just one, afaik :)

**Comment by estebanlm** [comment]
I think this is done? @jecisc ?

**Comment by jecisc** [comment]
IIRC we still have a few old layouts that could not be migrated to the new ones in the current state of the executable layouts.

**Comment by estebanlm** [comment]
done
