### ISSUE TITLE
Update OSWindow in Pharo 8

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#152]
ComposablePresenter>>openExternalWindowWithSpecLayout: should now be:

```Smalltalk
openExternalWindowWithSpecLayout: aSpec
	"Build the widget using the spec name provided as argument and display it into the world"

	^ self openWithSpecLayout: aSpec in: OSWindowWorldMorphModel
```

But since it is in Pharo we need to wait for Pharo 8

**Comment by MarcusDenker** [comment]
there is no method #openExternalWindowWithSpecLayout:  anymore in Pharo9 --> close
