### ISSUE TITLE
A label does not apply the #displayBackgroundColor

### ISSUE THREAD

**Issue by koendehondt** [pharo-spec/Spec#1524]
Consider this code:

```smalltalk
| mainLayout mainPresenter label |
mainPresenter := SpPresenter new.
label := mainPresenter newLabel
	label: 'Test';
	displayColor: [ Color red ];
	displayBackgroundColor: [ Color yellow ].
mainLayout := SpBoxLayout newLeftToRight
	add: label expand: false;
	yourself.
mainPresenter layout: mainLayout; open
```

It opens this window:

<img width="400" alt="Screenshot 2024-02-21 at 12 30 07" src="https://github.com/pharo-spec/Spec/assets/753271/3103f2ce-82e9-456f-a985-c45a35b994dd">

The red text is as expected.

But the background color of the label should be yellow, but apparently `displayBackgroundColor: [ Color yellow ]` has no effect.

**Comment by estebanlm** [comment]
meh, Text background and LabelMorphs are not playing very good together
