### ISSUE TITLE
Question about menubar height

### ISSUE THREAD

**Issue by koendehondt** [pharo-spec/Spec#1562]
Context: Pharo 12.

Is it normal and desired that a menubar is as high as it is now?

<img width="600" alt="Screenshot 2024-06-20 at 20 20 23" src="https://github.com/pharo-spec/Spec/assets/753271/c4e89121-c5f9-431b-8e68-bd0092a74e07">

The menu bar is 38 pixels high. That is higher than the toolbar, which is 32 pixels high. That seems to be incorrect.

Shouldn't it be more like this, when adding a menubar to a box layout (with expand: false)?

<img width="600" alt="Screenshot 2024-06-20 at 20 27 05" src="https://github.com/pharo-spec/Spec/assets/753271/3c692d1c-4e14-46fc-b3ca-50714098172c">

Here the height of the menubar is 23 pixels.

**Comment by astares** [comment]
I'd guess thats a bug. And I think nobody noticed as the Pharo tool windows mostly use toolbar only or apply menus only as context menus

**Comment by koendehondt** [comment]
Forgot to add the code to open the window:

```smalltalk
SpInitializeWindowExample new open
```

**Comment by estebanlm** [comment]
(doing a backport now)

**Comment by koendehondt** [comment]
I confirm that the issue is fixed in Pharo 12 and Pharo 13.
