### ISSUE TITLE
Slider presenter

### ISSUE THREAD

**Issue by tinchodias** [pharo-spec/Spec#1613]
- beHorizontal (default): doesn't work except when min=0 and max=1.
- beVertical doesn't work
- SpSliderPresenterBackendTest: only basic smoke tests + should end with "AdapterTest"

**Comment by tinchodias** [comment]
Like this, it works:
```smalltalk
s := SpSliderPresenter new.
s min: 0.
s max: 1.
s quantum: 0.1.
s value: 0.3.
s open.
```
Like this, it is broken:
```smalltalk
s := SpSliderPresenter new.
s min: 0.
s max: 10.
s quantum: 1.
s value: 3.
s open.
```
![giff](https://github.com/user-attachments/assets/4e2f82e3-de0f-4e78-a3e1-f454ee26f455)

**Comment by tinchodias** [comment]
The effect of `beVertical` is really weird:
```smalltalk
s := SpSliderPresenter new.
s min: 0.
s max: 10.
s quantum: 0.2.
s beVertical.
s open.
```
![giff2](https://github.com/user-attachments/assets/61d8eb8b-9e73-42dc-a65f-5a9a81e8e87e)
this is related to these sentences in `SpMorphicSliderAdapter>>#buildWidget`:
```smalltalk
	self presenter isHorizontal ifFalse: [ 
		preWidget := TransformationMorph new asFlexOf: preWidget.
		preWidget transform withAngle: 90 degreesToRadians negated ].
```

---

Nevertheless, the Morphic slider changes its orientation automatically by comparing width/height, as shown in this capture:
![giff3](https://github.com/user-attachments/assets/c7c16223-0e02-4617-b55c-9a45a5b49235)
So, the presenter's orientation is ignored.

**Comment by tinchodias** [comment]
Another sub-issue: the adapter tolerates string values, including a special care about fractions. See `SpMorphicSliderAdapter>>#value:`:
```smalltalk
value: aValue

	| value |	
	value := aValue isNumber
		ifTrue: [ aValue ] 
		ifFalse: [ 
			(aValue includes: $/)
				ifTrue: [ (NumberParser on: aValue) nextFraction ]
				ifFalse: [ aValue asNumber ] ].

	^ self presenter value: value asFloat
```
This is candidate to be removed. Just accept numbers is a better option.

**Comment by Ducasse** [comment]
Yes please what a bad idea. May be it should also accept XML, YAML, Java and more!
What a strange idea.

**Comment by tinchodias** [comment]
@Ducasse What is your opinion about orientation? 2 options:
- Remove beVertical and beHorizontal from the slider presenter API, and use the automatic orientation from the Morphic widget (and make other backends have this behavior)
- Remove the automatic orientation from Morphic widget and make beVertical and beHorizontal work.

Both presenter API orientation  and automatic orientation are not possible at the same time.

@estebanlm ?

**Comment by tinchodias** [comment]
More in the presenter API to be fixed:
<img width="651" alt="Screenshot 2024-10-03 at 20 26 53" src="https://github.com/user-attachments/assets/77744809-c3dd-4880-bd4d-9a2446e99e41">

**Comment by tinchodias** [comment]
Another bug: `SpSliderPresenter` has this API, but has no effect on the widget: 
```smalltalk
addMark: aString at: aValue
	"Add the mark `aString` at `aValue` ."
	
	^ self marks: (self marks
		add: (SpSliderMark new
			value: aValue;
			text: aString;
			yourself);
		yourself)
```
at least it has no senders, and I tested it with:
```smalltalk
s := SpSliderPresenter new.
s min: 0.
s max: 100.
s quantum: 1.
s value: 100.
s addMark: 'mid' at: 50.
s open.
```

**Comment by tinchodias** [comment]
Additionally, this widget supports a label in the background, and it works well if label is set before build. But when set after build, it only refreshes after some changes triggers the refresh:
<img width="1181" alt="Screenshot 2024-10-04 at 21 32 42" src="https://github.com/user-attachments/assets/80c45309-4706-40e0-96e3-b1661c360df8">

```smalltalk
s := SpSliderPresenter new.
s min: 0.
s max: 100.
s quantum: 1.
s value: 100.
s open.
s label: 'Label of Slider'.
```

**Comment by tinchodias** [comment]
Additionally, a slider can have a label. This works when set before open, but needs a manual action to trigger a refresh to show thie label when set after open:
![Oct-07-2024 18-08-38](https://github.com/user-attachments/assets/36ece210-220a-41c6-a10a-6816bd18f89e)
```smalltalk 
s := SpSliderPresenter new.
s min: 0.
s max: 100.
s quantum: 1.
s value: 100.
s open.
s label: 'Label of Slider'.
```

**Comment by tinchodias** [comment]
Not included in #1619:
* SpSliderPresenter>>color:
* SpSliderPresenter's marks API
* vertical/horizontal property (the widget determines the orientation in base on width/height ratio)

**Comment by estebanlm** [comment]
hi, @tinchodias 
no, `color:` should not be fixed, it should be removed.
color and that stuff needs to be defined through styles, not hardcoding it.

**Comment by tinchodias** [comment]
Thanks @estebanlm good point, I agree. I'm going to delete the color: method from `SpSliderPresenter`. No need to deprecate it as it is overriding an accessor from `SpAbstractWidgetPresenter`.

**Comment by tinchodias** [comment]
So, not yet included in https://github.com/pharo-spec/Spec/pull/1619:
* SpSliderPresenter's marks API **--> I can't find any traces in the slider Morph of these marks**
* vertical/horizontal property (the widget determines the orientation in base on width/height ratio)

I propose, for both cases, to remove the API. The alternatives would be a) to just deprecate instead of removing or b) implement it
