### ISSUE TITLE
Backport PluggableTextMorph changes from pharo and rewrite the input number

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#165]
A PR was integrated in Pharo to replace the usages of PluggableTextMorph by Rubric. 

The input text used it, so we should update it. 

Also, the input number is totally broken with this change and should be rewritten.

**Comment by plantec** [comment]
Hello, it should work with RubPluggableTextFieldMorph.
We can back port but I was thinking that conversions from String to application object should be the responsibility of the model.

**Comment by jecisc** [comment]
Hi, I got it to work with this PR:

https://github.com/pharo-spec/Spec/pull/166

I did not yet integrate it because I hope to use directly RubTextFieldMorph.
