### ISSUE TITLE
Unify inputs API

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#175]
Personally, I would love to have an `AbstractInputPresenter` defining a minimal API all inputs should answer to. 

For example, all inputs could be able to answer to:
- #whenAcceptDo:
- #whenChangedDo:
- #value
- #value: 
- #readOnly 
- #readOnly: 
- #disabled 
- #disabled:

**Comment by jecisc** [comment]
What does other thinks?

**Comment by juliendelplanque** [comment]
Definitely. I agree.

**Comment by pavel-krivanek** [comment]
agree

**Comment by estebanlm** [comment]
done I think. Reopen if not.
