### ISSUE TITLE
Could we have a Presenter class?

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#198]
Why having "Composable" presenter as base class if they are all composable?
What do you think?

**Comment by jecisc** [comment]
Check issue #74
Is that coherent with what you want?

**Comment by pavel-krivanek** [comment]
instead of the very generic Presenter, I would use something like SpecPresenter

**Comment by guillep** [comment]
Sure, that would be good too...

**Comment by jecisc** [comment]
Done.
