### ISSUE TITLE
Wrong selection announcements in FastTablePresenter 

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#200]
The following code fails in the thilrd assertion, while intuitively, all assertions should be ok:

```smalltalk
count := 0.
l := FastTablePresenter new.
l whenSelectionChanged: [ :s | s ifNotNil: [count := count + 1] ].

l items: #(1 2 3).
self assert: count = 0.

l setSelectedIndex: 1.
self assert: l selectedItem = 1.
self assert: count = 1.
```

**Comment by guillep** [comment]
The code could be transformed into a test very easily :)

**Comment by jecisc** [comment]
I plan to rework all the ListPresenter and deprecate the FastTablePresenter. 

Currently I am working on FastTable to implement missing features of TablePresenter. When this will be finished I’ll use the same kind of data source to change ListPresenter.

But yes, the tests would be greats. I’ll add it to my todolist.

**Comment by guillep** [comment]
This issue is certainly related

https://github.com/pharo-project/pharo/issues/2405

**Comment by jecisc** [comment]
Fixed.
