### ISSUE TITLE
Table with no columns throws strange error

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#205]
![image](https://user-images.githubusercontent.com/708322/51916183-10e99980-23dd-11e9-92e5-7bbb7544056e.png)

To reproduce:

```
TablePresenter new
	items: #(1 2 3);
	openWithSpec 
```

**Comment by guillep** [comment]
It seems that this is caused by adding a default (but entirely empty) column.
```
ensureAtLeastOneColumn
	self columns ifNotEmpty: [ ^ self ].
	self addColumn: self class defaultColumn
```

So the table uses that incorrect column when the table has elements.

**Comment by guillep** [comment]
Digging more, the column created by default with FastTable is a FTColumn, but the Adapter is expecting a Spec column (with a model). So maybe it's up to Spec to ensure there is at least a column?

**Comment by estebanlm** [comment]
I guess, but even in FT I was never convinced of this... but well, we can implement something similar at Spec level.

**Comment by guillep** [comment]
I'm not sure either, but I'd like to have working tests first. Then we can refactor and enhance whatever we want.

**Comment by jecisc** [comment]
Fixed
