### ISSUE TITLE
CI should now use Pharo 8

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#216]

**Comment by guillep** [comment]
Shouldn't it work for both?

**Comment by jecisc** [comment]
Both Pharo 7 and 8 you mean or Pharo 8 32bit and Pharo 8 64bit?

**Comment by guillep** [comment]
Pharo7 and Pharo8. We were able to support iceberg in two versions with no so much trouble. We should be able to do the same for Spec, and that would maximize our number of users.

**Comment by guillep** [comment]
We should have somehow the new fast table working on pharo 7 also, it
should not be so difficult.
