### ISSUE TITLE
add support for additional subpresenters map

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#218]
Currently, we are able to store sub-presenters only in instance variables. That prevents us from a more dynamic or declarative way of creation of sub-presenters. Let's add an additional dictionary to the presenters that users can use for storing of their presenters

**Comment by jecisc** [comment]
Currently, the design of DynamicComposablePresenter is a hack. 

I think Julien told me that it generates instance variables which must be really slow.

**Comment by estebanlm** [comment]
still I would like this to be a special kind of presenter, not part of the ComposablePresenter.

**Comment by pavel-krivanek** [comment]
I would solve it with own subclass but it, unfortunately, requires to inject the Spec interpreter.
