### ISSUE TITLE
NumberInputFieldPresenter is returning a string

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#223]
the `NumberInputFieldPresenter` is returning a string so users need to convert it. is it reasonable?

**Comment by pavel-krivanek** [comment]
If we will change it to return a number, then we should preserve an option to have an empty value (like nil). And ideally, have a configurable option to have a default value for invalid input.

VisualWorks are a cautionary example for us. Imagine that you have a number input field that is empty by default and button that will be enabled only in the case that the input field will not be empty. This button will clear the input field when pressed. In VW, as soon as you delete the content of the input field by keyboard, not using the button, the content of the field is set to "0" but the field is supposed to be empty so the button that may clear it will be not allowed. What is even funnier, if you write 0 there, you will get the same behavor!

**Comment by pavel-krivanek** [comment]
bump

**Comment by estebanlm** [comment]
I think if you ask for `value` you get the number?

**Comment by pavel-krivanek** [comment]
Right now, we have just `text`. It would definitely make sense to have more options in getting the entered number and formatting options.

**Comment by MarcusDenker** [comment]
There is no class NumberInputFieldPresenter?

**Comment by estebanlm** [comment]
there is `SpNumberInputFieldPresenter` but this is certainly outdated
