### ISSUE TITLE
ComposablePresenter is becoming super fat

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#225]
We should be careful with it not causing us problems in the future...

**Comment by jecisc** [comment]
With Esteban we wanted to remove everything window related. The new way is to set everything in #initializeWidow:.

This is a big change and should probably be done in two versions of Pharo. A first one deprecating all of that and saying to the user to use #initializeWindow: and the second to really remove these stuff.

**Comment by MarcusDenker** [comment]
ComposablePresenter is deprecated, I close the issue
