### ISSUE TITLE
Disabled checkboxes cannot be checked

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#233]
The Morphic checkboxes when disabled, they do not show checked state. Screenshots are from the modified demo application:
![pharoscreenshot 3](https://user-images.githubusercontent.com/572494/52046050-17dfeb80-2546-11e9-93c3-9154512c8557.png)
![pharoscreenshot 4](https://user-images.githubusercontent.com/572494/52046052-18788200-2546-11e9-9f60-19114920bc9d.png)

**Comment by jecisc** [comment]
Fixed.
