### ISSUE TITLE
Improve table presenter

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#242]
I'll improve a little the TablePresenter/TableBasedPresenter and add tests.

Also, I am wondering if we should not add methods #selectIndex: or #selectItem: instead of #selectedItem: and #selectedIndex: to make a better API. 

Maybe you have some thought on this @estebanlm ?

**Comment by estebanlm** [comment]
I prefer the action: `selectItem:`, but well... thing is how is the API around, we need to unify.
