### ISSUE TITLE
Spec concept of Application

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#244]
This is a feature request, proposal. 
Spec should have a first-class concept of Application.
- every presenter will have access to the related application. If the application will not be specified directly for the presenter, the application fo parent presenter will be used. As the default behavior, the presenter will ask its window.
- there should NOT be some kind of dynamic variable, global, singleton etc. The application should be the UI concept and if something without the direct UI binding will need to access the application, it should handle it on its own
- the main purpose of the application will be to manage the opened windows. The windows registry should allow named windows for easier navigation and management
- because the application will know its windows, it will be possible to manage modal windows blocking only the applications that belong to it
- the application may manage things like the application icon, name, it may be the settings provider, be involved in shortcuts management etc 
- I think that the application root presenters should not be restricted only to windows, some kind of subapplications would be handy for things like embedded Calypso etc.
- the application should provide good infrastructure to manage behavior of multi-window applications where you need to test if some action in one window affected correctly the other window content and so on

**Comment by pavel-krivanek** [comment]
Esteban is proposing to use it for the other resources than windows too...

**Comment by pavel-krivanek** [comment]
The application could be the entry point for standard dialogs like confirmation, file dialogs, warning windows etc. It would and should allow their replacement with the custom application specific ones

**Comment by pavel-krivanek** [comment]
related to: https://github.com/pharo-spec/Spec/issues/236

**Comment by pavel-krivanek** [comment]
in case you create only some simple tests with standalone presenters, we may use some concept of a stub application. However, maybe it should be explicit because there may be a significant danger of opening application windows without really assigned parent application. Thigs like #openWithSpec should be considered to be harmful.

**Comment by jecisc** [comment]
It seems good for me.

**Comment by pavel-krivanek** [comment]
the application could be a point for managing of multilingualization

**Comment by tesonep** [comment]
Styles also should be related with #253

**Comment by Ducasse** [comment]
Pavel I like the idea of application: I would name it ApplicationPresenter (managing all the windows of an application). 
Then for the Pharo tools I would make a specific subclass ToolPresenter that would in addition manage a list of named tools (like now the Smalltalk tools).

**Comment by jecisc** [comment]
Is the current concept of application enough for you @pavel-krivanek ?

**Comment by pavel-krivanek** [comment]
generally, yes
