### ISSUE TITLE
Labels are taking too much space

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#251]
in the following layout:

```
defaultSpec
	<spec>
	
	^ SpecBoxLayout newVertical
		  spacing: 5;
        add: (
            SpecBoxLayout newHorizontal
                add: (SpecBoxLayout newVertical
                    add: #label1 expand: false fill: true padding: 0;
                    add: #allNamesList;
                    yourself);
                add: (SpecBoxLayout newVertical
                    add: #label2 expand: false fill: true padding: 0;
                    add: #selectedNamesList; 
                    yourself);
                yourself);
        addLast: #deselectAll 
```
when the labels are short, the layout is vertically split in half as expected:

![pharo_sxnmhhr9sl](https://user-images.githubusercontent.com/572494/52700993-7317d200-2f79-11e9-83cb-920a8274f24a.png)

but when the first label is longer (but still not too long to be longer than the half of the window width), it already forces the layout to make the left half wider.

![pharo_weatwurd3d](https://user-images.githubusercontent.com/572494/52701230-081acb00-2f7a-11e9-8d7c-8f3a54cc95a4.png)

The same is for buttons with labels

**Comment by pavel-krivanek** [comment]
[SpecIssue251.zip](https://github.com/pharo-spec/Spec/files/2859712/SpecIssue251.zip)

**Comment by jecisc** [comment]
Should be fixed in the current spec.
