### ISSUE TITLE
ListPresenter does not have icons support

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#266]
The list presenter, unlike the FastTablePresenter, does not support icons for the list items. The DropListPresenter has them too. The support for them should be added.

**Comment by jecisc** [comment]
There is an icon list presenter. 

Now, maybe we can merge both. I guess they were two classes at the beginning because they were two in Morph.

**Comment by pavel-krivanek** [comment]
ah, cool. It should be probably merged... however, the icon list presenter has one small issue now... it does not display icons ;-)

**Comment by pavel-krivanek** [comment]
I will close this and open new issues

**Comment by estebanlm** [comment]
yes, it should be merged IMO
