### ISSUE TITLE
Renaming from widget to adapter broke some presenters

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#275]
Recently, it seems that ComposablePresenter>>widget was renamed #adapter. 

The problem is that Presenters and Adapters were polymorphic (both answered to #widget), now the method was renamed only in the Presenter but it can be called on both the Presenter or the Adaptor. 

If we trigger the transformation, Spec stops working because Adapters can't answer to #adapter. 

To see the problem, open the spec demo on Dynamic presenter then switch to another example.

**Comment by jecisc** [comment]
We also see that #widget is transformed into #adapter but it return `self spec`. The spec seems to be the adapter. 

We propose to deprecate #spec and to rename the variable #adapter to be more coherent. (Spec seems to be a concept of Spec that was removed some years ago by Benjamin)

**Comment by jecisc** [comment]
In fact, it's more complicated.

ComposablePresenter>>widget was returning its adapter. 
AbstractAdapter>>widget was returning its widget

At some places, one of those two could be a parameter to which we send #widget. Since there is a deprecation with transformation in ComposablePresenter>>widget those places were renamed to call #adaptor. But now the adaptors can receive this method and it's not as simple to fix than implementing #adaptor in it, because it needs to return its widget.

**Comment by guillep** [comment]
I can't reproduce the exact problem. In the latest commit, everything works except the dynamic example (which is ugly as an example btw). And it got broken since I changed the `resume` into `path`:

```smalltalk
"interpreting-private"
actionToPerformWithSelector: aSelector arguments: args
	^ [ spec perform: aSelector withArguments: args ]
		on: MessageNotUnderstood
		do: [ :ex | 
			"Maybe the message is not understood because we are trying to access a sub-part of a presenter but there is no accessor. In that case we can try to directly access the presenter.

			We are thinking of killing the interpreter. Maybe later if we know that we are getting the content of a variable of a presenter we can avoid using a catch and directly access the variable."
			(aSelector last ~= $: and: [ args isEmpty ])
				ifTrue: [ self subpresenterNamed: aSelector]
				ifFalse: [ ex resume ] ]
```

**Comment by guillep** [comment]
Aaaand that's because before we were eating the exception, and now we have it with us, in the real world :)

**Comment by guillep** [comment]
Restoring the `resume` seems to fix it, still the code is too brittle... I've added a log to see the exceptions there:

```
MessageNotUnderstood: SpecDemoDynamicMemoryGamePresenter>>isRedrawable
MessageNotUnderstood: SpecDemoDynamicMemoryGamePresenter>>isRedrawable
MessageNotUnderstood: receiver of "ifTrue:ifFalse:" is nil
MessageNotUnderstood: SpecDemoDynamicMemoryGamePresenter>>isRedrawable
MessageNotUnderstood: SpecDemoDynamicMemoryGamePresenter>>isRedrawable
MessageNotUnderstood: receiver of "ifTrue:ifFalse:" is nil
```

**Comment by guillep** [comment]
And only for that particular dynamic magic builder stuff presenter (not the others), we have
```
self adapter presenter == self
"false"
```

**Comment by guillep** [comment]
I've read the entire code of the interpreter, and I think I've found the issue. The interpreter uses the word `spec` all over the place, but its 99% of the times adapters that we have there. Somehow in the dynamic spec example (probably because of how it is built) it has a different build pattern, and it exits through the method `returnInterpretationOf:` which receives as argument a Presenter (and not an adaptor), and thus it sets a presenter as adaptor of another presenter (sometimes even generating a vicious loop).

The following seems to fix it.
```smalltalk
returnInterpretationOf: newInstance
	| result adaptor |
	result := self class interpretASpec: newInstance presenter: spec.
	adaptor := (result isKindOf: ComposablePresenter)
		ifTrue: [ self getAdaptorWithDefaultSpecOf: result ]
		ifFalse: [ result ].
	self presenter spec: adaptor.
	^ adaptor
```
