### ISSUE TITLE
Review TextPresenter>>#selectAll

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#290]
Currently, TextPresenter>>#selectAll ask to the backend to do the work. 

IMO it should be the responsibility of the Presenter, then the backend should be updated.

Do we agree on that?

The current implementation makes it harder to test because we need to open a Morphic instance of the presenter to launch a test instead of using the Stub binding.

**Comment by MarcusDenker** [comment]
the method is in a deprecated class --> I close the issue
