### ISSUE TITLE
the new Spec is breaking the pre-debug window

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#304]
the latest Spec broke the debugger, it ends in the emergency evaluator
`MultiColumnListPresenter>>displayBlock:` is missing
called from `GTSpecPreDebugWindow>>initializeStackPane`

**Comment by jecisc** [comment]
I'll look at this issue.

**Comment by jecisc** [comment]
I am looking at it and I see that all the display logic was removed and I do not see any equivalent. Did I miss something @guillep ?
