### ISSUE TITLE
Proposition: Special icon for presenters in system browser

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#31]
I have the impression it could help the users of Spec to get a visual information about what is a presenter. 

I propose to change the icons of the presenter like this:

![screen shot 2018-10-05 at 15 46 59](https://user-images.githubusercontent.com/9519971/46539250-43afd500-c8b6-11e8-91ed-c78fe790db37.png)

Objections?

**Comment by pavel-krivanek** [comment]
:+1:
