### ISSUE TITLE
Grid layout seems to add extra space at the beginning

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#312]
I used the grid layout for the buttons demo with this spec:

```Smalltalk
defaultSpec
	^ SpecGridLayout new
		beColumnHomogeneous;
		add: #buttonNormal at: 1 @ 1;
		add: #buttonDisabled at: 2 @ 1;
		add: #buttonWithIcon at: 3 @ 1;
		add: #buttonWithIconOnly at: 4 @ 1;
		add: #buttonHighlighted at: 5 @ 1;
		add: #buttonWithColor at: 1 @ 2;
		add: #buttonWithMenu at: 2 @ 2;
		add: #buttonWithShortcut at: 3 @ 2;
		add: #buttonWithHelp at: 4 @ 2;
		add: #buttonWithDifferentFont at: 5 @ 2
```

But I get extra space at the beginning:

![screenshot 2019-02-25 at 14 58 51](https://user-images.githubusercontent.com/9519971/53342335-0522c180-390e-11e9-80ef-10d13bddaf1b.png)

**Comment by jecisc** [comment]
This is caused by the border width set at 20. But in that case, I would expect it to be at the left AND right of the layout.

**Comment by estebanlm** [comment]
grid layout will adjust size of the panel to fit the elements inside. 
which means it will expand the panel size if necessary (don't ask me, is how it works).

In this case, you have the border at the right... is just that the panel expanded outside the window.
