### ISSUE TITLE
Remove Iceberg-related deprecation warnings

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#313]
Iceberg uses dialogs and tabs, which were replaced in the latest spec.

Making a release of spec with those deprecations makes iceberg raise tons of debuggers for nothing.

We should remove those deprecation warnings for now, and update iceberg

**Comment by estebanlm** [comment]
@guillep, this was already migrated.
Check https://github.com/pharo-vcs/iceberg/tree/feature/migrate-to-spec2

**Comment by guillep** [comment]
yes! but i want to integrate spec first without all those
