### ISSUE TITLE
Do a pass on MenuPresenter

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#317]
Menus are complicated: 
- any presenter may show a menu ?
- the way they are created may be backend dependent?
- setting them to a window is buggy (see #260)
- should (could?) they be dynamic (based on the selected item) or statically configured?

**Comment by tesonep** [comment]
- We should check if we should use the same presenter for menu bars and context menus.
- Check accelerators and shortcuts

**Comment by estebanlm** [comment]
done
