### ISSUE TITLE
Dirty packages after the spec loading

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#320]
after loading of the latest Spec, the package Spec-Layout and Spec-MorphicAdapters are dirty. It shows the changes in the method `AbstractMorphicAdapter>>#enabled`. After recalculation only the Spec-MorphicAdapter package is dirty

**Comment by pavel-krivanek** [comment]
that's an automatic refactoring

**Comment by pavel-krivanek** [comment]
fixed via https://github.com/pharo-spec/Spec/pull/321

**Comment by jecisc** [comment]
FIxed.
