### ISSUE TITLE
harvest changes from Pharo

### ISSUE THREAD

**Issue by guillep** [pharo-spec/Spec#334]
During all these months, things in Spec may have changed (recategorizations...). We should harvest them, but since lots of things have changed, the merge may be painful. So we should:
 - merge latest changes into the **FIRST** commit in spec
 - merge that commit into master

That would delegate all the merge pain to git

**Comment by jecisc** [comment]
Not long ago I did a synchronization with most of the changes. But since that time it's probably that some other happened.

Also when doing that, we should use the development version of Iceberg with the class instance variable deletion fix, else we will bring back unused class inst var.

**Comment by guillep** [comment]
Yes. Also, tagging the releases that we integrate in pharo will save us some of this syncing time in the future.

Regarding Iceberg, in my milestone I have to check the updates Esteban did and make a new release soon with the lastest fixes too.
