### ISSUE TITLE
Layout should position elements to the top by default

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#37]
![screen shot 2018-10-09 at 14 34 13](https://user-images.githubusercontent.com/9519971/46670328-2c345d00-cbd2-11e8-9c60-301ee8325e62.png)

**Comment by jecisc** [comment]
This seems to come from SpecLayout and not Morphic. 

I have a hard time to locate the problem because the code of the layouts does a lot of things with no comment.

**Comment by estebanlm** [comment]
we are going to deprecate that layout. 
it has sense spend time fixing it?

**Comment by jecisc** [comment]
We now have new layouts.
