### ISSUE TITLE
Objects that the SpecInterpreter creates, should have an owner

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#380]
Currently, the SpecInterpreter creates some other objects than presenters too and creates all of them with the `new` message. But they need to have an owner to be able to correctly bind the particular presenters to the application

**Comment by jecisc** [comment]
@pavel-krivanek Should we still spend some time on a deprecated layout?

**Comment by pavel-krivanek** [comment]
with the new layouts, let's close it
