### ISSUE TITLE
DialogWindowPresenter buttonBar should be optional

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#397]
as soon the buttonBar in the dialog does not contain any button (the application may provide custom alternatives inside the dialog), the space for it should not be reserved

**Comment by jecisc** [comment]
But does it make sense to have dialogues without buttons? Isn’t it a window?

**Comment by pavel-krivanek** [comment]
We do not have modal windows. If we will have the possibility to open general windows as modal then you are right.

**Comment by pavel-krivanek** [comment]
...and the dialog windows have usually different properties, like not allowed maximization etc.
