### ISSUE TITLE
Window presenter initial extent is not updatable

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#401]
WindowPresenter has a variable initial extent but there is no setter to this variable.

This is IMO bad because the goal is to move all window related behaviour in the #initializeWindow: method. If we cannot change its extent, we will not be able to remove this behaviour from ComposablePresenter.

What do you think @estebanlm?

**Comment by estebanlm** [comment]
not true. 
there is an initialExtent: method and is even a value holder (something I think is meh)

**Comment by jecisc** [comment]
Sorry for the noise. It was added recently and my image was too old .
