### ISSUE TITLE
Should we really deprecate whenSelectedItemChangedDo: & co?

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#402]
I wonder if all the deprecated method of lists should really be deprecated. 

For example: #whenSelectedItemChangedDo:

I find it annoying that I need to manage a selection object when I need only a really simple list. Here I  have a project where I only need the method #item: and #whenSelectedItemChangedDo:, I do not want to use a selection object.

Can't we keep those methods and throw an error is the selection strategy does not work with the method?

**Comment by MarcusDenker** [comment]
there are two method #whenSelectedItemChangedDo:, none is deprecated. I close the issue
