### ISSUE TITLE
TextInput acceptBlock is not rejecting the input

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#407]
The acceptBlock of TextInput should be able to reject the entered text but it seems to do not do that. It is the same for auto-accept turned off.

```
textInput := TextInputFieldPresenter new.
textInput autoAccept: true.
textInput whenTextChangedDo: [ :aText | aText logCr ].
textInput acceptBlock: [ :aText | 
	Transcript show: 'rejecting: '; show: aText; cr.
	false ].
textInput openWithSpec.
```

So the early validation of the input is not possible. Maybe the validation API should be synchronized to fit GTK more too...

This is the way how I needed to do the number input in past, check the text when it was already changed and privately change it if it contained wrong input (but this approach is not suitable for some other kind of validation)
```
self number1Input whenTextChanged: [ 
		| receivedText newText |
		receivedText := self number1Input text asString.
		newText := receivedText select: [ :aCharacter | aCharacter isDigit ].
		newText = receivedText ifFalse: [ 
			self number1Input textHolder rawValue: newText.
			self number1Input textHolder valueChanged: newText] ]
```

**Comment by estebanlm** [comment]
not valid anymore
