### ISSUE TITLE
Every exception creates a new Morphic UI process

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#421]
With the latest Spec, if a pre-debug window is opened (like for every deprecation warning that I do not turn off - and we have a lot of them), a new Morphic UI process is created which causes the unpredictable image behavior.

I'm not sure if it is limited to just pre-debug windows of to the full debugger too

**Comment by pavel-krivanek** [comment]
It looks to be caused only by the pre-debug window... probably this windows raises a deprecation warning exception or something like that which causes the new UI process to be created for safety reasons...

**Comment by estebanlm** [comment]
fixed in b1d1da8
