### ISSUE TITLE
ComposablePresenter>>registerKeyStrokesForNextFor: references to Morphic implementation

### ISSUE THREAD

**Issue by estebanlm** [pharo-spec/Spec#43]
This implementation: 

```Smalltalk
registerKeyStrokesForNextFor: aWidget

	aWidget ifNil: [ ^ self ].
	
	self eventKeyStrokesForNextFocus do: [:each |
		aWidget bindKeyCombination: each toAction: [ self giveFocusToNextFrom: self ] ]
```

Assumes "widget" is a Morphic widget.
While we can demand that api from any component we use, I think this violates proper layering. 

Maybe we should kick this into the adapter?
Or we just accept is like that?

**Comment by jecisc** [comment]
I agree that the Presenter should not assume the API of the concrete widget. It should go to the adapter IMO.

**Comment by pavel-krivanek** [comment]
go to the adapter, definitelly

**Comment by MarcusDenker** [comment]
This is a method in a deprecated class. I think we can close the issue
