### ISSUE TITLE
loading of the latest Spec is ignored by baselines

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#498]
When you use Spec in the baseline, something like: 
```
	spec 
		baseline: 'Spec' 
		with: [ spec repository: 'github://pharo-spec/Spec:master/src' ]
```
Then the latest Spec version is ignored by metacello and the latest image version is used. 

It may be related to the Spec-Deprecated warnings in interactive loading regime.

**Comment by jecisc** [comment]
Fixed.
