### ISSUE TITLE
SpecDemoTreeTablePresenter gives errors on events

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#500]
SpecDemoTreeTablePresenter new openWithSpec

and then right click on an item ->  MessageNotUnderstood: TreeTablePresenter>>contextMenu

or double click on an item       -> MessageNotUnderstood: TreeTablePresenter>>activatesOnDoubleClick

**Comment by MarcusDenker** [comment]
class SpecDemoTreeTablePresenter does not exist anymore. I close the issue
