### ISSUE TITLE
TreeTablePresenter "whenSelectionChangedDo:" gives the wrong selection

### ISSUE THREAD

**Issue by 570gina** [pharo-spec/Spec#503]
This is an example, then I added the code to the SpecDemoTreeTablePresenter.
```treeTablePresenter whenSelectionChangedDo: [ :selection | selection inspect ]```

![image](https://user-images.githubusercontent.com/24423847/56905125-f6889000-6a9f-11e9-80bd-bfc67bd1c778.png)
I selected the "AbsolutePath" item, but selection shows the "Stream" item.

**Comment by astares** [comment]
Yes - saw the same effect when using TreeTablePresenter. Selectio problem seem to be starting at the second or third level in the tree.
