### ISSUE TITLE
using AbtractListPresenter>>#FilterBlock: and Selecting an item doesn't select the correct item

### ISSUE THREAD

**Issue by GDayne** [pharo-spec/Spec#512]
I am using a ListPresenter with a filter, but every time I use the filter and select an item, the selection is old item in that position.
![Screen Shot 2019-05-15 at 16 01 42](https://user-images.githubusercontent.com/11018772/57781922-757df980-772b-11e9-9e76-544f62a040cd.png)
![Screen Shot 2019-05-15 at 16 01 59](https://user-images.githubusercontent.com/11018772/57781930-7a42ad80-772b-11e9-9de4-ef4e67c639f6.png)
For example here I want to show the classes in the package selected.
In the first image I am selecting the package with no filter, everything works fine.
In the second image I am using the filter with "Caly" and selecting an item in the second position, but the clases are wrong. Because it's evaluation the old list with no filter and the index

**Comment by kgardas** [comment]
Not sure if your analysis of the bug behavior is correct, but I guess I'm also hit by the same issue while writing some software on top of Pharo 8. I've been able to perfectly duplicate the issue by using Pharo's provided Spec2 examples. To duplicate please go to Help -> Spec2 Examples. And there select Lists demo. On the 3rd list please type "Adapter" into the Filter box, and then select the first item of the list which should be "AbstractAdapter". After selection, you will see below the listing inside the label text "Selection from list 3: AColorSelectorMorth. Now, if you remove the filter value and allow list to redraw, you will see that AColorSelectorMorth is exacly first item. You can repeat the same and select whatever item number from the list and then verify that selection contains really the list item of the selected index from the original list. So IMHO, selection and selection detection works on the original unfiltered list while it should be working on the filtered one.
Anyway, I'm still not able to fix this issue yet.

**Comment by estebanlm** [comment]
this is related to #871
please, see the explanation there

**Comment by estebanlm** [comment]
this issue has been resolved in #871
