### ISSUE TITLE
[ImagePresenter]#switchAutoscale get a blank image

### ISSUE THREAD

**Issue by 570gina** [pharo-spec/Spec#553]
I created an image and added the switchAutoscale method.
Then I got a blank(white) image. (but the image value is still nil)
![image](https://user-images.githubusercontent.com/24423847/58485212-e24db680-8163-11e9-8351-7830f62f56be.png)
After building the widget, I set ```self imagePresenter image: nil```, I got this image below.
![image](https://user-images.githubusercontent.com/24423847/58485262-fb566780-8163-11e9-89be-ef7eeefdef39.png)

I would like to clear the blank(white) image at the beginning.

**Comment by jecisc** [comment]
The problem comes from Morph directly.
