### ISSUE TITLE
Add new announcement WidgetWillBeBuilt

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/Spec#576]
Add a new announcement WidgetWillBeBuilt that will be invoked immediately before the widget will be built as completion to the current announcement WidgetBuilt.

This announcement may be used in situations when you want to, for example, to modify the context of a context menu just before it will be displayed to the user.

**Comment by pavel-krivanek** [comment]
```smalltalk

num := 1.
b := ButtonPresenter new.
menu := MenuPresenter new.
menu whenWillBeBuiltDo: [ 
	menu addItem: [ :item | 
		item name: num asString; action: [ self inform: item name ].
		num := num + 1 ] ].
b contextMenu: menu.
b openWithSpec
```

**Comment by pavel-krivanek** [comment]
fixed by https://github.com/pharo-spec/Spec/commit/80a1691ebd9b8e970d3c0625ca8a25903262966e

**Comment by estebanlm** [comment]
I disagree with this.
context menus are valuables. 
Which means you can put a block and evaluate each time. 
Why you need yet-another-announcement for that?

**Comment by pavel-krivanek** [comment]
but this valuable will not be executed each time the user invokes the menu. Or am I wrong? Can you provide an alternative example to the one above?

**Comment by jecisc** [comment]
If you give a block instead of a menu presenter, the menu will be rebuild at each invocation. 

On top of that you can also use #visible: and #enabled: on items giving them a block in case you do not want to rebuild it but still want to have conditions.

**Comment by estebanlm** [comment]
yes, you are wrong :)
it is evaluated each time.

**Comment by estebanlm** [comment]
example

```Smalltalk
num := 1.
b := ButtonPresenter new.
b contextMenu: [ 
    | menu |
    menu := MenuPresenter new.
    menu addItem: [ :item | 
	item name: num asString; action: [ self inform: item name ].
	num := num + 1 ].
    menu ].
b openWithSpec
```

**Comment by pavel-krivanek** [comment]
it is broken but it may be fixed easily. 

```
MorphicButtonAdapter>>#menu:

menu: aMenu
	| menuPresenter |

	menuPresenter := self model contextMenu.
	menuPresenter ifNil: [ ^ nil ].
	^ SpecBindings
		value: self model application adapterBindings
		during: [ menuPresenter value buildWithSpec ]

MorphicButtonAdapter>>#showSubMenuIfPresent

showSubMenuIfPresent
	| aContextMenu |
	aContextMenu := self model contextMenu value.
	aContextMenu
		ifNotNil: [ aContextMenu menuGroups isEmpty
				ifFalse: [ subMenuWidget
						ifNotNil: [ subMenuWidget delete.
							subMenuWidget := nil ].
					subMenuWidget := (MorphicMenuAdapter
						adaptAsPopup: self model contextMenu) widget.
					subMenuWidget
						popUpAdjacentTo:
							{self widget bounds bottomLeft.
							self widget bounds bottomRight}
						forHand: ActiveHand
						from: self widget.
					subMenuWidget popUpOwner: self ] ]```

however, then it has huge issues when you click on the button with LMB. End if you try to fix that, whenever it tries to ask the model, the block is evaluated. In the case of LMB, the block is evaluated 4-times

**Comment by pavel-krivanek** [comment]
the version with announcement does not recreate the menu on LMB at all ;-)

**Comment by pavel-krivanek** [comment]
question: shouldn't the button menu and context menu of the button be two separate things?
