### ISSUE TITLE
Deprecate Array>>#asSpLayout

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#593]
At some point, we will need to deprecate Array>>asSpLayout. We can't now because it's too much used.

**Comment by estebanlm** [comment]
more than deprecate, all SpLayout stuff should be removed (along with interpreter things). I think Deprecation warning does not applies here (since people will need to replace this part to use Spec2 anyway).

**Comment by MarcusDenker** [comment]
the method has been removed in Pharo9, thus --> close
