### ISSUE TITLE
Check skiped tests

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#641]
Esteban added new tests around non implemented features. 

To get a green CI i skiped them. We should make them green.

Tests: 

- SpMorphicGridLayoutTests>>#testColumnHomogeneousDiferentRowsAndColumns
- SpMorphicGridLayoutTests>>#testColumnNotHomogeneousPairedRowsAndColumns
- SpMorphicGridLayoutTests>>#testLayoutIn
- SpMorphicGridLayoutTests>>#testSpanColumn
- SpMorphicGridLayoutTests>>#testSpanRow

**Comment by MarcusDenker** [comment]
All these tests are not skipped anymore
