### ISSUE TITLE
Toolbars should have the style to allow the label below the icons.

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/Spec#648]
![image](https://user-images.githubusercontent.com/355455/60975886-f7a22d00-a32c-11e9-8c10-6af8a0403d45.png)

Also, it will be nice to have the ability to scale the icons in the toolbar.

**Comment by astares** [comment]
I guess label positioning should be possible on **top, left, right** and below the icon (**bottom**). This would allow for icons like 

![image](https://user-images.githubusercontent.com/5980033/60983469-44d8cb80-a33a-11e9-81f9-b558e03cc56a.png)

**Comment by astares** [comment]
Idealy we would have: 
- Toolbar
- ToobarButton
- ToolbarButtinWithIcon 
and so on. Combined an ability for the toolbar to support sections (with or wouthout a diver) and adding / layouting any spec widget we would be very flexible
