### ISSUE TITLE
StandardFonts defaultFont should be available from SpPresenter

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#662]

**Comment by Ducasse** [comment]
Else we will have StandardFonts defaultFont everywhere.

**Comment by jecisc** [comment]
Does it make sense to have it on presenters? Because this will only be useful for the projects rendered in Pharo. Not for GTK, a possible future Seaside binding, etc.

**Comment by estebanlm** [comment]
yes, this is not a problem of Spec but Morphic. 
Nevertheless, Spec needs to define a way to style presenters (and font to use should be part of a style, not a global variable).
We need to introduce the style mechanism for morphic backend soon.

**Comment by estebanlm** [comment]
done with styles
