### ISSUE TITLE
what's the usage of ComposablePresenterWithModel?

### ISSUE THREAD

**Issue by estebanlm** [pharo-spec/Spec#67]
Do we really need it?

**Comment by pavel-krivanek** [comment]
Since I introduced it, I think yes ;-)

http://forum.world.st/Spec-Improved-way-of-linking-presenters-to-domain-model-objects-td4988907.html

See the class comment and the Spec-Demo From example comment. It was created to solve real-life issues with binding of Spec applications to data sources.
