### ISSUE TITLE
change "value holders" with slots?

### ISSUE THREAD

**Issue by estebanlm** [pharo-spec/Spec#68]
I think we may benefit a lot by using slots instead populating all presenters with value holder objects all around. 
Yes, this is just a way to "hide" the behaviour. But having a property slot will make everything cleaner.

**Comment by jecisc** [comment]
Julien had the same feeling. We planned to open an issue about it. So I would say: yes. No more `xxx value` everywhere!

**Comment by dorellang** [comment]
I wonder, what would be the API for this? :P

**Comment by jecisc** [comment]
We now have SpObservableSlot and use them. I do not close the issue because we still use some NewValueHolder. We can close after we finish migrating.

**Comment by estebanlm** [comment]
this is mostly done
