### ISSUE TITLE
Add back support of Spec 10 to access nested subcomponents

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#703]
Now with this change it works

resolvePresenter: presenterNameOrLayout model: aModel bindings: bindings

	"most common case: I receive a symbol that I need to convert into a presenter"
	presenterNameOrLayout isSymbol ifTrue: [ 
		^ (self subpresenterOrLayoutNamed: presenterNameOrLayout of: aModel)
			ifNil: [ self error: 'You presenter named "', presenterNameOrLayout , '" from ', aModel printString ,' was not initialized.' ] ].
	
	"I receive a layout: dig inside."
	presenterNameOrLayout isSpLayout ifTrue: [ 
		^ presenterNameOrLayout buildAdapterFor: aModel bindings: bindings ].

	presenterNameOrLayout isArray ifTrue: [ 
			| current |
			current := aModel. 
			presenterNameOrLayout
				do: [ :each | current := (self subpresenterOrLayoutNamed: each of: current) ].
			^ current 
			].
	
	"I receive an arbitrary object (needs to understand #asPresenter)"
	^ presenterNameOrLayout asPresenter
		owner: aModel;
		yourself

**Comment by jecisc** [comment]
After a discussion, we do not want to support that.
