### ISSUE TITLE
Rework hierarchy of presenters

### ISSUE THREAD

**Issue by jecisc** [pharo-spec/Spec#74]
Currently, we have ComposablePresenter that represent all kinds of presenters and all of them can be opened in windows.

We should re-work this hierarchy to have:
- LeafPresenters
- CompositePresenters
- WindowablePresenters

![image](https://user-images.githubusercontent.com/9519971/47087511-7f369180-d21c-11e8-9d82-9eb21b6274f3.png)

**Comment by guillep** [comment]
Well, the fact that we can open any presenter inside a window is not bad per se I think (unless the implementation is very bad?).
Also, What's the difference between all of them? Do they have different behaviour?

**Comment by jecisc** [comment]
Change of hierarchy was done.
