### ISSUE TITLE
Add a way to put separators in context menu

### ISSUE THREAD

**Issue by Inao0** [pharo-spec/Spec#743]
As it was done in Iceberg in Spec 1 :
![image](https://user-images.githubusercontent.com/37711386/63338400-0673fa80-c343-11e9-8f14-a0ce4f76bdf4.png)

**Comment by estebanlm** [comment]
There is a way: each group will be divided with a separator :)

**Comment by jecisc** [comment]
In Commander2 I think you need to have a group with sub groups.

**Comment by estebanlm** [comment]
yeah, but commander2 ~= spec2 ;)
