### ISSUE TITLE
ObserveableSlots should be provided as a separated project

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-spec/Spec#757]
I might want to use them in a headless context.

**Comment by astares** [comment]
We should move them to the regular out of the box slot package of the Pharo base image, no?

**Comment by juliendelplanque** [comment]
This option would be ok for me as well.
It will happen as Spec2 will be integrated in Pharo
However, it would be better in a package separated from Spec packages.

**Comment by astares** [comment]
Yes - Slots might be part of a minimalistic image without Spec and ObserveableSlots might be useful for that as well. 

We should ask @estebanlm and marcus if ObserveableSlots could be shifted to the regular slots package.

**Comment by juliendelplanque** [comment]
I created an issue in Pharo repository as one can see above.

**Comment by astares** [comment]
Markus told me yesterday on WhatsApp that it will be provided (but with better name and better implementation)

**Comment by MarcusDenker** [comment]
We do have ObserverableSlot in the image and migrating Spec to use it
