### ISSUE TITLE
customizable row height in a list

### ISSUE THREAD

**Issue by demarey** [pharo-spec/Spec#783]
In a list presenter, it would be nice to allow to specify the row (cell) height.

**Comment by demarey** [comment]
also true for tables and maybe trees

**Comment by tinchodias** [comment]
I am interested in this feature, too. I found in a recent version that it is possible in some way, with:
~~~
presenterItems := Smalltalk ui icons icons values collect: #asPresenter.
p := SpComponentListPresenter new.
p presenters: presenterItems.
p openWithSpec.
~~~
But I wanted to use it with SpTextPresenters, and it didn't work:
~~~
texts := {
'1'.
'1
2'.
'1
2
3' }.

items := texts collect: [:each |
	SpTextPresenter new
		text: each;
		yourself ].

p := SpComponentListPresenter new.
p presenters: items.
p openWithSpec.
~~~

**Comment by estebanlm** [comment]
this is now possible on a SpComponentListPresenter (not in the other lists, however... and it will not be because there is not a simple way to express this).
So, no tables or trees. Just ComponentLists

**Comment by estebanlm** [comment]
ah, and the row height is not specified, it is just calculated with the height of the presenter you include into the component list.

**Comment by estebanlm** [comment]
@tinchodias what didn't work? 
Maybe the height of the text presenters is not determined (because a problem on SpStyle) and then, there is no possible row height calculation.

**Comment by tinchodias** [comment]
After writing that, I discovered that RubScrolledTextMorph that Spec2 uses doesn't return the height that I'd expect (the height that is required to have all the text visible). 
Instead, the RubEditingArea that the RubScrolledTextMorph wraps does return the height and it works.
