### ISSUE TITLE
TablePresenter misses selection support and tests

### ISSUE THREAD

**Issue by demarey** [pharo-spec/Spec#786]
No selection by item
No unselection
No tests on selection

**Comment by estebanlm** [comment]
they are in the superclass

**Comment by demarey** [comment]
update : it is not SpTablePresenter but SpTreeTablePresenter

**Comment by demarey** [comment]
PR to come.
Please re-open

**Comment by estebanlm** [comment]
Mmm. How do you plan to open an item in a tree? 
Will you pass a path of objects?

**Comment by demarey** [comment]
There is already a way to select items by path. I extended it to be able to select by item. You just give the item you want to select and then it performs a breadth first search in the tree returning the path and then call selectByPath:

**Comment by estebanlm** [comment]
yeah, that's what I was fearing :)
I'm not sure about this mechanism, it beats the purpose of being lazy ;)
