### ISSUE TITLE
SpTreeTablePresenter performance issues

### ISSUE THREAD

**Issue by eilx2** [pharo-spec/Spec#811]
There are some performance issues related to SpTreeTablePresenter with multiple selection enabled. Take for example this code:

```smalltalk
| tree |
tree := SpTreeTablePresenter new.
tree 
	roots: { Object  }; 
	children: [ :each | each subclasses ];
	beMultipleSelection.

tree 
	selectPaths: (
		(1 to: (Object subclasses size)) collect: [:each | { 1. each }]).
tree openWithSpec
```

If you try to expand a node then the GUI is going to hang.

**Comment by fedemennite** [comment]
Seems to be fixed. Can be closed in our opinion.
