### ISSUE TITLE
SpTreeTablePresenter scrolling when expanding

### ISSUE THREAD

**Issue by eilx2** [pharo-spec/Spec#812]
Consider the following code:

```smalltalk
| tree |
tree := SpTreeTablePresenter new.
tree 
	roots: { Object  }; 
	children: [ :each | each subclasses ];
	beMultipleSelection;
	selectPath: { 1 . (Object subclasses size) }.


tree openWithSpec
```

After the window is opened, scroll to the top and expand the "Exception" node without selecting it. If you expand this node the tree table is going to scroll back to the last element which is not an expected behaviour.

**Comment by tinchodias** [comment]
I just downloaded a Pharo 9 and tried to reproduce this issue without success. 
Should we close it?

**Comment by fedemennite** [comment]
We believe this can be closed. It works for us.

**Comment by Ducasse** [comment]
Thanks for the feedback. Esteban is sick at home :)
