### ISSUE TITLE
Use consistently "Sp" namespace prefix for Spec classes/traits

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#813]
The namespace prefix for classes and traits in Spec2 was defined as "Sp", so we have 

 - ... many classes correctly prefixed with "Sp" 
 - **SpTMorphicUIRedrawer** trait
 - **SpTContextMenu** trait

But we unfortunately also have 

NO NAMESSPACE PREFIX
================
 - **TEyeInspectorActions** -> should be SpTEyeInspectorActions

NAMESPACE PREFIX not at the beginning
===========================
 - **TSpDynamicPresenter**  -> should be SpTDynamicPresenter
 - **TSpHaveWrappingScrollBars** -> should be SpTHaveWrappingScrollBars
 - **TSpHaveWrappingScrollBars** -> should be SpTHaveWrappingScrollBars
 - **TSpMorphicTableDataSourceCommons** -> should be SpTMorphicTableDataSourceCommons
 - **TSpObservable** -> should be SpTObservable  (or switched to a general Observer)

We should (re)name them to be consistent before they get used from other sides (ideally in Pharo 8)

**Comment by astares** [comment]
Seems to be fixed in [https://github.com/pharo-spec/Spec/releases/tag/v0.2.0](https://github.com/pharo-spec/Spec/releases/tag/v0.2.0)

**Comment by estebanlm** [comment]
it is :)

**Comment by astares** [comment]
@estebanlm Thanks!
