### ISSUE TITLE
Cannot open a presenter in world (DNU #asSpLayout)

### ISSUE THREAD

**Issue by demarey** [pharo-spec/Spec#822]
I want to open an SpApplication as full world.
To achieve so, `#run` is defined as follows:
```Smalltalk
self 
		open: aPresenter 
		withSpecLayout: aPresenter defaultSpec
		using: SpWorldPresenter
```
When running the app, I get a DNU because the default layout returned by `SpWorldPresenter` (when calling #retrieveDefaultSpec) is a `SpMorphPresenter` (see `SpWorldPresenter>>#defaultSpec`).
Maybe `#buildWindowWithLayout:presenterLayout:` should be redefined for `SpWorldPresenter`

**Comment by estebanlm** [comment]
SpWorldPresenter is not supported (and probably will not be supported). 
Why would you want something like that ?

**Comment by demarey** [comment]
Copy of the comment:

> This way, every spec application can be opened as the Pharo system window as window, to simulate native a application.

That is what is used for Pharo Launcher.
I think we need something like that.

**Comment by MarcusDenker** [comment]
the fix was merged, we can close the issue
