### ISSUE TITLE
dialog modal is broken since a month or two...

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#853]
Taken from the techtalk

openDialogWithSpec is not modal anymore.

```
addFilm
	| dialog windowPresenter |
	dialog := ImdbFilmPresenter newApplication: self application.
	windowPresenter := dialog openDialogWithSpec.
	windowPresenter isOk
		ifFalse: [ ^ self ].
	"how would you do it differently?"
	ImdbFilm
		addFilm:
			(ImdbFilm new
				name: dialog nameText text;
				director: dialog director text;
				year: dialog yearNumber number).
	self updatePresenter
```

**Comment by Ducasse** [comment]
Was this bug fixed?

**Comment by Ducasse** [comment]
it was used in the dead book on spec2

https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/blob/master/Chapters/CaseStudyOne/CaseStudyOne.pillar

**Comment by guillep** [comment]
It seems that in morphic, Dialogs are not modal (which are two different concepts).
Should all dialogs be by default? That's a decision that should be taken at the spec level to ensure consistency.

Here is a workaround that makes dialog windows modal.

```smalltalk
SpMorphicDialogWindowAdapter >> open

	self model isCentered 
		ifTrue: [ self centered ].
	
	self widget openModal.    <======================
	self model initialPosition ifNotNil: [
		self widget position: self model initialPosition ].
	
	self windowIsOpening
```

But this probably means that `open` should be refactored into a template method to allow hooking the real opening in the subclasses.

**Comment by guillep** [comment]
Once I've done that, I've tested it with:

```
windowPresenter := SpButtonPresenter new openDialogWithSpec.
self inform: windowPresenter isOk asString.
```

Modality works, but the window is never closed by default when clicking on `Ok` or `Cancel` is that ok?

**Comment by estebanlm** [comment]
I just fixed that upstream.
