### ISSUE TITLE
spec2 is not Pharo 8 compatible

### ISSUE THREAD

**Issue by demarey** [pharo-spec/Spec#867]
Some tests do not pass on Pharo 8.
ex: SpListCommonPropertiesTest has 8 failing tests because of the following error:
`#MorphicRenderLoop is missing, and does not understand #new`

MorphicRenderLoop is present in Pharo 9 but not in Pharo 8.

**Comment by estebanlm** [comment]
yes, Spec2 will not be Pharo compatible because of changes on the MorphicRenderingLoop and how we adapt it.
if super-needed, we can do a compatibility package?

**Comment by Ducasse** [comment]
Tx christophe 
for now if super-needed is false :)
