### ISSUE TITLE
Not possible to resize window with spec2

### ISSUE THREAD

**Issue by gbosetti** [pharo-spec/Spec#872]
Hello, I'm trying to open a SpPresenter of 900x600. Suchpresenter has a notebook with diverse pages. The pages are dynamically loaded and if I change the size of its components (with the constraints) the components are hidden, the size of the presenter never changes. So I tried:

initializeWindow: aWindow
	aWindow window window bounds: (window window bounds origin corner: (900@600)).

Such line of code works from the inspector. But when executed from initializeWindow: it doesn't always work. Sometimes the window is smaller, sometimes it is bigger.

I already tried by overriding the openWithSpec method and executing such a line after the super openWithSpec, but it doesn't work at all. 

Any idea how to support the resizing?

**Comment by estebanlm** [comment]
you cannot do that.

1. initializeWindow: receive a presenter that is not yet instantiated (it will be instantiated later),
2. I would never ever use or allow such an ugly api like `aWindow window window...` etc. (how many "windows" are there? Not speaking about demerers law.

So, you have a SpWindowPresenter... what can you do with that? you have `initialExtent:` and `initialPosition:` there!
