### ISSUE TITLE
Removing classes from ChangeSorter throws DNU

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#873]
See Pharo issue  https://github.com/pharo-project/pharo/issues/6260

Easy to fix: 

see https://github.com/pharo-project/pharo/pull/6261 (which is a PR for Pharo 9)

![image](https://user-images.githubusercontent.com/5980033/80681519-28707000-8ac1-11ea-8ff1-d81d1d3fc4d7.png)

**Comment by astares** [comment]
Already fixed in P9 image, need to be done in Spec2 as well
https://github.com/pharo-project/pharo/pull/6261

**Comment by MarcusDenker** [comment]
Prs are merged
