### ISSUE TITLE
Add cursor manipulation message/s

### ISSUE THREAD

**Issue by JacobGood1** [pharo-spec/Spec#875]
Spec should include the ability to manipulate the cursor. This feature will allow people to create text editing facilities among other things. I am not sure where the message should be installed, I will leave that up to the Spec implementers. 

Possible names for the message:
displaceCursor:
moveCursor:
cursorPositionIndex:
cursorPosition:

**Comment by estebanlm** [comment]
`cursorPositionIndex:` and `cursorPosition` were implemented in 102e225
