### ISSUE TITLE
SpCodePresenter directly references RBParser

### ISSUE THREAD

**Issue by StephanEggermont** [pharo-spec/Spec#879]
Code presenters should be usable for all kinds of code. The parser, completer and highlighter should be selectable (and default to Smalltalk). 

This is relevant in the image when using the RBPatternParser, and otherwise when supporting editing code in other languages like SQL or Javascript

**Comment by StephanEggermont** [comment]
Affects
SpCodePresenter>>#findClassFrom: 
SpPharoStyler>>#parseAST:

**Comment by estebanlm** [comment]
no, is not.
this is not a generic `SpCodePresenter` but a `SpPharoPresenter` and is correct like that. 
For a generic code presenter, there will be (and some are on their way) a `SpRichTextPresenter` hierarchy (we are already working on a `SpPillarTextPresenter`, for example.
It you want to work with a different source code, it is there where you have to look for/see (but this is still very incomplete).

**Comment by StephanEggermont** [comment]
Uhm, no? We have support in-image for code rewriting and that needs a different parser.

**Comment by estebanlm** [comment]
Yes. You want a different parser you subclass `SpRichTextPresenter` and you implement It there :)
(side note: even `SpCodePresenter` will become a subclass of `SpRichTextPresenter`)

**Comment by estebanlm** [comment]
side note: `#findClassFrom:` will most probably be moved to a command as I am not sure it belongs there.
side note two: `SpPharoStyler` is not used for the moment in the system... but yes, it will be the place where Pharo style will be placed in the future.
