### ISSUE TITLE
SpApplication should define iconNamed: and iconManager

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#880]
for the book

[SpApplication-iconManager.txt](https://github.com/pharo-spec/Spec/files/4672629/SpApplication-iconManager.txt)
[SpApplication-iconManagerSetter.txt](https://github.com/pharo-spec/Spec/files/4672630/SpApplication-iconManagerSetter.txt)
[SpApplication-iconNamed.txt](https://github.com/pharo-spec/Spec/files/4672631/SpApplication-iconNamed.txt)

**Comment by estebanlm** [comment]
In 2cebe332fc3ea73cfc26617205babfc6ab1d8c6a
