### ISSUE TITLE
Loading Spec generates an error

### ISSUE THREAD

**Issue by riVDM** [pharo-spec/Spec#896]
Hello,

I get this error when executing the script:
Metacello new
        githubUser: 'pharo-spec' project: 'Spec' commitish: 'master' path: 'src';
        baseline: 'Spec2';
        onConflict: [ :e | e useIncoming ];
        onUpgrade: [ :e | e useIncoming ];
        ignoreImage;
        load

![SpecError](https://user-images.githubusercontent.com/67067876/85271340-f6eda280-b47a-11ea-8dc7-4ffb9b8d4ef6.png)

Thank you for help!
Richard

**Comment by estebanlm** [comment]
I cannot reproduce this. 
Which version of Pharo are you using?

**Comment by riVDM** [comment]
I’m using Pharo 8 64 bit stable with GToolkit on Mac OS X Sierra
  Van de Moosdijk

**Comment by estebanlm** [comment]
Hi, 
Spec2 is Pharo9+ exclusive, it will not load in Pharo8 or previous. 
Thanks for report anyway :)

**Comment by riVDM** [comment]
Hi,
Thanks! I’ll try to migrate to Pharo 9.

  Van de Moosdijk
