### ISSUE TITLE
SpDemoDynamicMemoryGamePresenter looks broken

### ISSUE THREAD

**Issue by astares** [pharo-spec/Spec#899]
in recent Pharo 9 image this one just looks unusable.

![image](https://user-images.githubusercontent.com/5980033/86637587-184fa200-bfd6-11ea-8cef-b661be18823e.png)

Slider does not move and nothing more is displayed.

I guess it is needed to fix it, or redoit using current api

Pharo9.0.0
Build information: Pharo-9.0.0+build.466.sha.811706578b9c3fb1a8c37717959759d35a3d9ea8 (64 Bit) on Windows

**Comment by tinchodias** [comment]
This issue is fixed after #1619.
I mean, it should be fixed now. I didn't try it.
Please close if you can. I don't have permissions.

**Comment by astares** [comment]
SpDemoDynamicMemoryGamePresenter from 'Spec2-Examples-Demo-Dynamic' package
is not in Pharo 13 anymore. I guess it had been removed from the demos.
