### ISSUE TITLE
Popover does not close

### ISSUE THREAD

**Issue by ClotildeToullec** [pharo-spec/Spec#901]
When clicking on another window, a popover can be hidden behind this window but not dismissed.
Moreover, it is not dismissed when the window from which it originates is closed.
In the end, we can have many orphan popovers.

![Spec-Popover](https://user-images.githubusercontent.com/39184695/87952635-58208a00-caaa-11ea-9d95-fd9e7dde0305.gif)
![Popover-Midas](https://user-images.githubusercontent.com/39184695/87954347-8bfcaf00-caac-11ea-9916-71e24c829d65.gif)

**Comment by estebanlm** [comment]
this was fixed upstream (sorry not to point it before)
