### ISSUE TITLE
SpOpenOnStringExample: checkbox changes layout only once

### ISSUE THREAD

**Issue by tinchodias** [pharo-spec/Spec#902]
I looked at `SpOpenOnStringExample`, which works but only for the first activation. When deactivated there is no layout update.

Install script in latest P9 was:
```smalltalk
    Metacello new
        githubUser: 'pharo-spec' project: 'Spec' commitish: 'master' path: 'src';
        baseline: 'Spec2';
        onConflict: [ :e | e useIncoming ];
        onUpgrade: [ :e | e useIncoming ];
        ignoreImage;
        load
```

**Comment by estebanlm** [comment]
that example is not valid anymore, all layouts are dynamic now and you do not need (or can) use it like that.
Thanks to point to that example, I will remove it :)
anyway, today you do this: 
```Smalltalk
self layout: myNewLayout
```
and that should work :)

**Comment by tinchodias** [comment]
Thanks, so... I close it.
