### ISSUE TITLE
newHorizontal -> should be -> newColumnElements / newVertical -> should be -> newRowElements

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#924]
I have a stupid question
I wanted to have two columns side by side
now in spec I have to write

```
defaultSpec 

    ^ (SpBoxLayout newVertical
            add: (SpBoxLayout newHorizontal 
                        add: #topicList ;
                        add: #reportText;
                        yourself);
            yourself)
```

and I do not understand why this is not an horizontal box with a vertical box with two columns inside.
Why do I have to have a vertical and inside two horizontal elements. This confuses me totally.
I can never understand why I think the inverse.
or it means that horizontal means that you add one after the one horizontally two elements.
To me the horizontal vs horizontally is different.
In any case newHorizontal is a bad name if this is that you add columns inside.
in that newColumns would be a lot better
and probably vertical means that you add something on top of the other and this is case newRows would be a lot better.

**Comment by Ducasse** [comment]
Discussing with Pablo

newHorizontal should be renamed newLeftToRightColumns
newVertical should be renamed newTopToBottomRows

S.

**Comment by demarey** [comment]
I personally find the current selectors meaningful: #newVertical creates a new vertical layout. Each element added to a vertical layout is below the previous one. Samfe for #newHorizontal that creates an horizontal layout where a new element is added to the right of the previous one.

If I take your example, the following should be enough to have 2 columns:
```smalltalk
^ SpBoxLayout newHorizontal
     add: #topicList ;
     add: #reportText;
     yourself
```
I prefer newHorizontal over newLeftToRightColumns.

**Comment by Ducasse** [comment]
Are you sure that you just to not get use to it? Because now I'm spoiled and I learned by heart that newHorizontal is in fact  newLeftToRightColumns (So basically that you add a **vertical** element one after the other).
I did a test with Marcus and he got confused. I'm pretty sure that if we ask around people will get confused. 

I think that renaming newHorizontal newLeftToRightColumns and newVertical newTopToBottomRows is a good move because you can never be confused with them. You add columns and rows and you do not have to guess.

**Comment by demarey** [comment]
> Are you sure that you just to not get use to it? 

Could be. Hard to say ;)

> Because now I'm spoiled and I learned by heart that newHorizontal is in fact newLeftToRightColumns (So basically that you add a **vertical** element one after the other).

I do not understand where you see **vertical** elements in this example. You add a first element in the horizontal layout (1st widget), then the second (2nd widget at the right of the first one). If you really want columns, you need to add a vertical layout for each column you want in an horizontal layout.

> I did a test with Marcus and he got confused. I'm pretty sure that if we ask around people will get confused.

To me the key thing is to think that we are creating a **layout**. If the layout is horizontal, all elements added to it will be stacked horizontally.

> I think that renaming newHorizontal newLeftToRightColumns and newVertical newTopToBottomRows is a good move because you can never be confused with them. You add columns and rows and you do not have to guess.

I do not like the concept of columns or rows because it is a subset of what you can do with a layout. It adds a connotation like if you are building a grid / spreadsheet. Maybe #newLeftToRightLayout ?

**Comment by estebanlm** [comment]
while I got used to newVertical and newHorizontal and I kind of like them, we also implemented `newtopToBottom` and `newLeftToRight`.
