### ISSUE TITLE
PragmaCollector allInstances do: #reset

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#928]
- Took 
Pharo 9.0.0
Build information: Pharo-9.0.0+build.626.sha.7e9033b2d47ceab8504ea5dff2881e1ba7e6ea57 (64 Bit)
- did 
```
  Metacello new
        githubUser: 'pharo-spec' project: 'Spec' commitish: 'master' path: 'src';
        baseline: 'Spec2';
        onConflict: [ :e | e useIncoming ];
        onUpgrade: [ :e | e useIncoming ];
        ignoreImage;
        load
```

Should do 
- PragmaCollector allInstances do: #reset

**Comment by MarcusDenker** [comment]
I think due to removing the use of PragmaCollector everywhere this might not be needed anymore?

**Comment by MarcusDenker** [comment]
as PragmaCollector is not used, we can close this
