### ISSUE TITLE
Data in tree tables columns are not correctly separated in their own columns

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/Spec#929]
Here is an example from the debugger, but this is the same problem with spec2 tree table example.

![Screenshot 2020-08-28 at 20 44 27](https://user-images.githubusercontent.com/26929529/91604686-6ac29480-e96f-11ea-9f2f-07f90aa5c174.png)

**Comment by StevenCostiou** [comment]
Same problems with tables

**Comment by estebanlm** [comment]
is a problem with the headers, I was working on that before leaving on vacances (and is a problem with FT, not spec... but I will need to fix it anyway) :)

**Comment by estebanlm** [comment]
fixed in https://github.com/pharo-spec/Spec/releases/tag/v0.7.5
