### ISSUE TITLE
[Feature Request] add a SpListWithFilterPresenter

### ISSUE THREAD

**Issue by jordanmontt** [pharo-spec/Spec#938]
As the filtering functionality is removed of SpListPresenter, I think that will be very useful to have a filtering list presenter.
The name can be: SpListWithFilterPresenter. This can be achieved using a high level component that has an SpListPresenter and SpTextInputFieldPresenter.
I have been working on this and I think that I found a solution but the code must be reviewed.

**Comment by Ducasse** [comment]
Yes totally. Everybody is reimplementing it and this is a lost of ressources and uniformity.
