### ISSUE TITLE
Can not change extension of popover

### ISSUE THREAD

**Issue by tinchodias** [pharo-spec/Spec#941]
Hello, I tried setting the `extent:`of the contained presenter but didn't work. 

To do my try, I updated this method of the demo: `SpPopoverExample>>#showPopover:relativeTo:`

~~~Smalltalk
showPopover: aPosition relativeTo: aPresenter

	| newPresenter |
	newPresenter := SpPresenter new 
			layout: (SpBoxLayout newVertical
				borderWidth: 10; 
				spacing: 5;
				add: (self newLabel label: 'A cool popup!');
				add: (self newButton 
					label: 'Dismiss';
					action: [ popover dismiss ];
					yourself);
				yourself);
			yourself.

	popover ifNotNil: [ popover dismiss ].
	(popover := self newPopover)
		relativeTo: aPresenter;
		position: aPosition;
		presenter: newPresenter;
		popup.
		
	newPresenter extent: 700@700.
~~~

**Comment by tinchodias** [comment]
I did it on a P9 downloaded today, the Spec version sould be 0.7.3

**Comment by estebanlm** [comment]
you cannot manually change an extension of *any* presenter, not just the popover (this is not supported like that anymore).
A presenter will adopt the size of its inner presenters, depending in the arrangement determined by the layout.

**Comment by tinchodias** [comment]
Thanks, then I should try to style it. In my case, it was acceptable to have a predefined fixed size for any possible contents of the popover.
