### ISSUE TITLE
no visual feedback that a new panel is added to the right of the Miller list

### ISSUE THREAD

**Issue by demarey** [pharo-spec/Spec#954]
**Describe the request**
There is no visual feedback that a new panel is added to the right of the Miller list when inspecting in the debugger.
Also, when navigating the miller list, you cannot know where you are in the list.

**Expected behavior**
Inspector should scroll automatically to the newly created panel.
Miller list should also provide a visual feedback: create a dotted list with one dot for each pane and show the current selection in the list.

**Screenshots**
![debugger-enh-inspector](https://user-images.githubusercontent.com/2494203/95566953-92068a00-0a22-11eb-96e8-b9cdad22883a.gif)

**Comment by estebanlm** [comment]
fixed in https://github.com/pharo-spec/Spec/releases/tag/v0.7.5
