### ISSUE TITLE
Wrong layout in some special conditions

### ISSUE THREAD

**Issue by tinchodias** [pharo-spec/Spec#984]
This is how it looks in Iceberg:

![imagen](https://user-images.githubusercontent.com/3044265/98724286-48d38e00-2372-11eb-9e97-9fd21c1c961a.png)

I tried to isolate what are the conditions for this problem, that happens in the rita2 branch of iceberg when you select a repository and select "Commit". It wasn't easy for me to find a small example to reproduce the issue but I finally got one that I put below. (Or, at least, it reproduces a problem that looks quite the same as in Iceberg):

```smalltalk
innerPresenter := SpPresenter new.
tree := innerPresenter newTreeTable
	addColumn: (SpStringTableColumn evaluated: #name);
	children: [ :aClass | aClass subclasses ];
	yourself.
innerPresenter layout:
	(SpPanedLayout newHorizontal
		position: 79 percent;
		add: tree;
		add: innerPresenter newDiff;
		yourself).

outerPresenter := SpPresenter new.
outerPresenter layout:
	(SpBoxLayout newVertical
		add: innerPresenter;
		add: outerPresenter newButton height: 25;
		yourself).

tree roots: { Object }.
outerPresenter openWithSpec.
```

Note for Esteban: First I thought that sending `expandAll` after `roots:` was producing the problem, but no, it's independent from this.

**Comment by tinchodias** [comment]
This still happens

**Comment by tinchodias** [comment]
I found a small workaround in the `IceTipDiffPanel` of Iceberg where this issue was present:

```
initializePresenters

	super initializePresenters.
...
	self defer: [ self update ].

```
The deferred update does it.

**Comment by estebanlm** [comment]
this is the same as #1006
