### ISSUE TITLE
Remove unused variables

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Spec#997]
UnusedVariableRemover new unusedVariables inspect

Should do the same for class variables

**Comment by MarcusDenker** [comment]
The easiest to find them is to run testNoUnusedInstanceVariablesLeft from the browser and look at the "remaining" temp

Class Variable are all fixed

**Comment by MarcusDenker** [comment]
Two more:
- remove unused ivars is SpMorphicLabelAdapter, SpMorphicSpinnerAdapter and SpDemoMenuButtonPresenter #1050
- Dead-code-SpTestingComposablePresenterWithAdditionalPresenters #1051

**Comment by MarcusDenker** [comment]
all done! testNoUnusedInstanceVariablesLeft is now green
